/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CallListResponse,
    CallListResponseFromJSON,
    CallListResponseToJSON,
} from '../models/CallListResponse';
import {
    type CallRecording,
    CallRecordingFromJSON,
    CallRecordingToJSON,
} from '../models/CallRecording';
import {
    type CallRecordingListResponse,
    CallRecordingListResponseFromJSON,
    CallRecordingListResponseToJSON,
} from '../models/CallRecordingListResponse';
import {
    type CreateCallRequest,
    CreateCallRequestFromJSON,
    CreateCallRequestToJSON,
} from '../models/CreateCallRequest';
import {
    type CreateMeetingRoomRequest,
    CreateMeetingRoomRequestFromJSON,
    CreateMeetingRoomRequestToJSON,
} from '../models/CreateMeetingRoomRequest';
import {
    type MeetingRoom,
    MeetingRoomFromJSON,
    MeetingRoomToJSON,
} from '../models/MeetingRoom';
import {
    type SpatioCall,
    SpatioCallFromJSON,
    SpatioCallToJSON,
} from '../models/SpatioCall';
import {
    type UpdateParticipantStateRequest,
    UpdateParticipantStateRequestFromJSON,
    UpdateParticipantStateRequestToJSON,
} from '../models/UpdateParticipantStateRequest';

export interface CreateCallOperationRequest {
    createCallRequest?: CreateCallRequest;
}

export interface CreateMeetingRoomOperationRequest {
    createMeetingRoomRequest: CreateMeetingRoomRequest;
}

export interface DeleteCallRecordingRequest {
    recordingId: string;
}

export interface EndCallRequest {
    id: string;
}

export interface GetCallRequest {
    id: string;
}

export interface GetMeetingRoomRequest {
    id: string;
}

export interface JoinCallRequest {
    id: string;
}

export interface LeaveCallRequest {
    id: string;
}

export interface ListCallRecordingsRequest {
    id: string;
}

export interface StartCallRecordingRequest {
    id: string;
}

export interface StopCallRecordingRequest {
    id: string;
    recordingId: string;
}

export interface UpdateCallParticipantStateRequest {
    id: string;
    updateParticipantStateRequest: UpdateParticipantStateRequest;
}

export interface WorkspaceCreateCallRequest {
    org: string;
    workspace: string;
    requestBody: { [key: string]: any; };
}

export interface WorkspaceCreateMeetingRoomRequest {
    org: string;
    workspace: string;
    requestBody: { [key: string]: any; };
}

export interface WorkspaceDeleteCallRecordingRequest {
    org: string;
    workspace: string;
    recordingId: string;
}

export interface WorkspaceEndCallRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceGetBandwidthHistoryRequest {
    org: string;
    workspace: string;
}

export interface WorkspaceGetBandwidthSummaryRequest {
    org: string;
    workspace: string;
}

export interface WorkspaceGetCallRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceGetMeetingRoomRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceJoinCallRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceLeaveCallRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceListActiveCallsRequest {
    org: string;
    workspace: string;
}

export interface WorkspaceListCallRecordingsRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceStartCallRecordingRequest {
    org: string;
    workspace: string;
    id: string;
}

export interface WorkspaceStopCallRecordingRequest {
    org: string;
    workspace: string;
    id: string;
    recordingId: string;
}

export interface WorkspaceUpdateCallParticipantRequest {
    org: string;
    workspace: string;
    id: string;
    requestBody: { [key: string]: any; };
}

/**
 * 
 */
export class CallsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCall without sending the request
     */
    async createCallRequestOpts(requestParameters: CreateCallOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCallRequestToJSON(requestParameters['createCallRequest']),
        };
    }

    /**
     * Start a new call.
     */
    async createCallRaw(requestParameters: CreateCallOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SpatioCall>> {
        const requestOptions = await this.createCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpatioCallFromJSON(jsonValue));
    }

    /**
     * Start a new call.
     */
    async createCall(requestParameters: CreateCallOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SpatioCall> {
        const response = await this.createCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMeetingRoom without sending the request
     */
    async createMeetingRoomRequestOpts(requestParameters: CreateMeetingRoomOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createMeetingRoomRequest'] == null) {
            throw new runtime.RequiredError(
                'createMeetingRoomRequest',
                'Required parameter "createMeetingRoomRequest" was null or undefined when calling createMeetingRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/rooms`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMeetingRoomRequestToJSON(requestParameters['createMeetingRoomRequest']),
        };
    }

    /**
     * Create a persistent meeting room.
     */
    async createMeetingRoomRaw(requestParameters: CreateMeetingRoomOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeetingRoom>> {
        const requestOptions = await this.createMeetingRoomRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeetingRoomFromJSON(jsonValue));
    }

    /**
     * Create a persistent meeting room.
     */
    async createMeetingRoom(requestParameters: CreateMeetingRoomOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeetingRoom> {
        const response = await this.createMeetingRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCallRecording without sending the request
     */
    async deleteCallRecordingRequestOpts(requestParameters: DeleteCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recordingId'] == null) {
            throw new runtime.RequiredError(
                'recordingId',
                'Required parameter "recordingId" was null or undefined when calling deleteCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/recordings/{recordingId}`;
        urlPath = urlPath.replace('{recordingId}', encodeURIComponent(String(requestParameters['recordingId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a recording.
     */
    async deleteCallRecordingRaw(requestParameters: DeleteCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a recording.
     */
    async deleteCallRecording(requestParameters: DeleteCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCallRecordingRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for endCall without sending the request
     */
    async endCallRequestOpts(requestParameters: EndCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling endCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/end`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * End a call (host only).
     */
    async endCallRaw(requestParameters: EndCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.endCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * End a call (host only).
     */
    async endCall(requestParameters: EndCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.endCallRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getBandwidthHistory without sending the request
     */
    async getBandwidthHistoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/bandwidth/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Time-series bandwidth metrics.
     */
    async getBandwidthHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.getBandwidthHistoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Time-series bandwidth metrics.
     */
    async getBandwidthHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getBandwidthHistoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBandwidthSummary without sending the request
     */
    async getBandwidthSummaryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/bandwidth/summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Aggregate bandwidth metrics.
     */
    async getBandwidthSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.getBandwidthSummaryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Aggregate bandwidth metrics.
     */
    async getBandwidthSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getBandwidthSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCall without sending the request
     */
    async getCallRequestOpts(requestParameters: GetCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a call.
     */
    async getCallRaw(requestParameters: GetCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SpatioCall>> {
        const requestOptions = await this.getCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpatioCallFromJSON(jsonValue));
    }

    /**
     * Fetch a call.
     */
    async getCall(requestParameters: GetCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SpatioCall> {
        const response = await this.getCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMeetingRoom without sending the request
     */
    async getMeetingRoomRequestOpts(requestParameters: GetMeetingRoomRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMeetingRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/rooms/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a meeting room.
     */
    async getMeetingRoomRaw(requestParameters: GetMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeetingRoom>> {
        const requestOptions = await this.getMeetingRoomRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeetingRoomFromJSON(jsonValue));
    }

    /**
     * Fetch a meeting room.
     */
    async getMeetingRoom(requestParameters: GetMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeetingRoom> {
        const response = await this.getMeetingRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for joinCall without sending the request
     */
    async joinCallRequestOpts(requestParameters: JoinCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling joinCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/join`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Join a call.
     */
    async joinCallRaw(requestParameters: JoinCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.joinCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Join a call.
     */
    async joinCall(requestParameters: JoinCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.joinCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for leaveCall without sending the request
     */
    async leaveCallRequestOpts(requestParameters: LeaveCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling leaveCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/leave`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Leave a call.
     */
    async leaveCallRaw(requestParameters: LeaveCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.leaveCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Leave a call.
     */
    async leaveCall(requestParameters: LeaveCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.leaveCallRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listActiveCalls without sending the request
     */
    async listActiveCallsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List active calls.
     */
    async listActiveCallsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallListResponse>> {
        const requestOptions = await this.listActiveCallsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallListResponseFromJSON(jsonValue));
    }

    /**
     * List active calls.
     */
    async listActiveCalls(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallListResponse> {
        const response = await this.listActiveCallsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCallRecordings without sending the request
     */
    async listCallRecordingsRequestOpts(requestParameters: ListCallRecordingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listCallRecordings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/recordings`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List recordings for a call.
     */
    async listCallRecordingsRaw(requestParameters: ListCallRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRecordingListResponse>> {
        const requestOptions = await this.listCallRecordingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRecordingListResponseFromJSON(jsonValue));
    }

    /**
     * List recordings for a call.
     */
    async listCallRecordings(requestParameters: ListCallRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRecordingListResponse> {
        const response = await this.listCallRecordingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startCallRecording without sending the request
     */
    async startCallRecordingRequestOpts(requestParameters: StartCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/recordings/start`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start a recording (host only).
     */
    async startCallRecordingRaw(requestParameters: StartCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRecording>> {
        const requestOptions = await this.startCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRecordingFromJSON(jsonValue));
    }

    /**
     * Start a recording (host only).
     */
    async startCallRecording(requestParameters: StartCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRecording> {
        const response = await this.startCallRecordingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stopCallRecording without sending the request
     */
    async stopCallRecordingRequestOpts(requestParameters: StopCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stopCallRecording().'
            );
        }

        if (requestParameters['recordingId'] == null) {
            throw new runtime.RequiredError(
                'recordingId',
                'Required parameter "recordingId" was null or undefined when calling stopCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/recordings/{recordingId}/stop`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{recordingId}', encodeURIComponent(String(requestParameters['recordingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop an in-progress recording.
     */
    async stopCallRecordingRaw(requestParameters: StopCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRecording>> {
        const requestOptions = await this.stopCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRecordingFromJSON(jsonValue));
    }

    /**
     * Stop an in-progress recording.
     */
    async stopCallRecording(requestParameters: StopCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRecording> {
        const response = await this.stopCallRecordingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCallParticipantState without sending the request
     */
    async updateCallParticipantStateRequestOpts(requestParameters: UpdateCallParticipantStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCallParticipantState().'
            );
        }

        if (requestParameters['updateParticipantStateRequest'] == null) {
            throw new runtime.RequiredError(
                'updateParticipantStateRequest',
                'Required parameter "updateParticipantStateRequest" was null or undefined when calling updateCallParticipantState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/calls/{id}/participant`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateParticipantStateRequestToJSON(requestParameters['updateParticipantStateRequest']),
        };
    }

    /**
     * Toggle participant audio/video/screen-share state.
     */
    async updateCallParticipantStateRaw(requestParameters: UpdateCallParticipantStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.updateCallParticipantStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Toggle participant audio/video/screen-share state.
     */
    async updateCallParticipantState(requestParameters: UpdateCallParticipantStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateCallParticipantStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceCreateCall without sending the request
     */
    async workspaceCreateCallRequestOpts(requestParameters: WorkspaceCreateCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceCreateCall().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceCreateCall().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling workspaceCreateCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     */
    async workspaceCreateCallRaw(requestParameters: WorkspaceCreateCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceCreateCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceCreateCall(requestParameters: WorkspaceCreateCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceCreateCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceCreateMeetingRoom without sending the request
     */
    async workspaceCreateMeetingRoomRequestOpts(requestParameters: WorkspaceCreateMeetingRoomRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceCreateMeetingRoom().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceCreateMeetingRoom().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling workspaceCreateMeetingRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/rooms`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     */
    async workspaceCreateMeetingRoomRaw(requestParameters: WorkspaceCreateMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceCreateMeetingRoomRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceCreateMeetingRoom(requestParameters: WorkspaceCreateMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceCreateMeetingRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceDeleteCallRecording without sending the request
     */
    async workspaceDeleteCallRecordingRequestOpts(requestParameters: WorkspaceDeleteCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceDeleteCallRecording().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceDeleteCallRecording().'
            );
        }

        if (requestParameters['recordingId'] == null) {
            throw new runtime.RequiredError(
                'recordingId',
                'Required parameter "recordingId" was null or undefined when calling workspaceDeleteCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/recordings/{recordingId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{recordingId}', encodeURIComponent(String(requestParameters['recordingId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceDeleteCallRecordingRaw(requestParameters: WorkspaceDeleteCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workspaceDeleteCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workspaceDeleteCallRecording(requestParameters: WorkspaceDeleteCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workspaceDeleteCallRecordingRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workspaceEndCall without sending the request
     */
    async workspaceEndCallRequestOpts(requestParameters: WorkspaceEndCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceEndCall().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceEndCall().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceEndCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/end`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceEndCallRaw(requestParameters: WorkspaceEndCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workspaceEndCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workspaceEndCall(requestParameters: WorkspaceEndCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workspaceEndCallRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workspaceGetBandwidthHistory without sending the request
     */
    async workspaceGetBandwidthHistoryRequestOpts(requestParameters: WorkspaceGetBandwidthHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceGetBandwidthHistory().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceGetBandwidthHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/history`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceGetBandwidthHistoryRaw(requestParameters: WorkspaceGetBandwidthHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceGetBandwidthHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceGetBandwidthHistory(requestParameters: WorkspaceGetBandwidthHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceGetBandwidthHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceGetBandwidthSummary without sending the request
     */
    async workspaceGetBandwidthSummaryRequestOpts(requestParameters: WorkspaceGetBandwidthSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceGetBandwidthSummary().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceGetBandwidthSummary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/summary`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceGetBandwidthSummaryRaw(requestParameters: WorkspaceGetBandwidthSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceGetBandwidthSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceGetBandwidthSummary(requestParameters: WorkspaceGetBandwidthSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceGetBandwidthSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceGetCall without sending the request
     */
    async workspaceGetCallRequestOpts(requestParameters: WorkspaceGetCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceGetCall().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceGetCall().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceGetCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceGetCallRaw(requestParameters: WorkspaceGetCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceGetCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceGetCall(requestParameters: WorkspaceGetCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceGetCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceGetMeetingRoom without sending the request
     */
    async workspaceGetMeetingRoomRequestOpts(requestParameters: WorkspaceGetMeetingRoomRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceGetMeetingRoom().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceGetMeetingRoom().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceGetMeetingRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/rooms/{id}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceGetMeetingRoomRaw(requestParameters: WorkspaceGetMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceGetMeetingRoomRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceGetMeetingRoom(requestParameters: WorkspaceGetMeetingRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceGetMeetingRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceJoinCall without sending the request
     */
    async workspaceJoinCallRequestOpts(requestParameters: WorkspaceJoinCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceJoinCall().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceJoinCall().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceJoinCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/join`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceJoinCallRaw(requestParameters: WorkspaceJoinCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceJoinCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceJoinCall(requestParameters: WorkspaceJoinCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceJoinCallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceLeaveCall without sending the request
     */
    async workspaceLeaveCallRequestOpts(requestParameters: WorkspaceLeaveCallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceLeaveCall().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceLeaveCall().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceLeaveCall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/leave`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceLeaveCallRaw(requestParameters: WorkspaceLeaveCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workspaceLeaveCallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workspaceLeaveCall(requestParameters: WorkspaceLeaveCallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workspaceLeaveCallRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workspaceListActiveCalls without sending the request
     */
    async workspaceListActiveCallsRequestOpts(requestParameters: WorkspaceListActiveCallsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceListActiveCalls().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceListActiveCalls().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceListActiveCallsRaw(requestParameters: WorkspaceListActiveCallsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceListActiveCallsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceListActiveCalls(requestParameters: WorkspaceListActiveCallsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceListActiveCallsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceListCallRecordings without sending the request
     */
    async workspaceListCallRecordingsRequestOpts(requestParameters: WorkspaceListCallRecordingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceListCallRecordings().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceListCallRecordings().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceListCallRecordings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceListCallRecordingsRaw(requestParameters: WorkspaceListCallRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceListCallRecordingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceListCallRecordings(requestParameters: WorkspaceListCallRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceListCallRecordingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceStartCallRecording without sending the request
     */
    async workspaceStartCallRecordingRequestOpts(requestParameters: WorkspaceStartCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceStartCallRecording().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceStartCallRecording().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceStartCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/start`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceStartCallRecordingRaw(requestParameters: WorkspaceStartCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceStartCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceStartCallRecording(requestParameters: WorkspaceStartCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceStartCallRecordingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceStopCallRecording without sending the request
     */
    async workspaceStopCallRecordingRequestOpts(requestParameters: WorkspaceStopCallRecordingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceStopCallRecording().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceStopCallRecording().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceStopCallRecording().'
            );
        }

        if (requestParameters['recordingId'] == null) {
            throw new runtime.RequiredError(
                'recordingId',
                'Required parameter "recordingId" was null or undefined when calling workspaceStopCallRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/{recordingId}/stop`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{recordingId}', encodeURIComponent(String(requestParameters['recordingId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workspaceStopCallRecordingRaw(requestParameters: WorkspaceStopCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceStopCallRecordingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceStopCallRecording(requestParameters: WorkspaceStopCallRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceStopCallRecordingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workspaceUpdateCallParticipant without sending the request
     */
    async workspaceUpdateCallParticipantRequestOpts(requestParameters: WorkspaceUpdateCallParticipantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling workspaceUpdateCallParticipant().'
            );
        }

        if (requestParameters['workspace'] == null) {
            throw new runtime.RequiredError(
                'workspace',
                'Required parameter "workspace" was null or undefined when calling workspaceUpdateCallParticipant().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workspaceUpdateCallParticipant().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling workspaceUpdateCallParticipant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/participant`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{workspace}', encodeURIComponent(String(requestParameters['workspace'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     */
    async workspaceUpdateCallParticipantRaw(requestParameters: WorkspaceUpdateCallParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.workspaceUpdateCallParticipantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async workspaceUpdateCallParticipant(requestParameters: WorkspaceUpdateCallParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.workspaceUpdateCallParticipantRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
