/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type Conversation,
    ConversationFromJSON,
    ConversationToJSON,
} from '../models/Conversation';
import {
    type ConversationMessage,
    ConversationMessageFromJSON,
    ConversationMessageToJSON,
} from '../models/ConversationMessage';
import {
    type CreateConversationRequest,
    CreateConversationRequestFromJSON,
    CreateConversationRequestToJSON,
} from '../models/CreateConversationRequest';
import {
    type SaveMessageRequest,
    SaveMessageRequestFromJSON,
    SaveMessageRequestToJSON,
} from '../models/SaveMessageRequest';
import {
    type UpdateConversationRequest,
    UpdateConversationRequestFromJSON,
    UpdateConversationRequestToJSON,
} from '../models/UpdateConversationRequest';
import {
    type UpdateMessageMetadataRequest,
    UpdateMessageMetadataRequestFromJSON,
    UpdateMessageMetadataRequestToJSON,
} from '../models/UpdateMessageMetadataRequest';

export interface CreateConversationOperationRequest {
    createConversationRequest?: CreateConversationRequest;
}

export interface DeleteConversationRequest {
    id: string;
}

export interface GetConversationRequest {
    id: string;
}

export interface GetLatestConversationForContextRequest {
    context: string;
}

export interface ListConversationMessagesRequest {
    id: string;
    limit?: number;
    before?: string;
}

export interface ListConversationsRequest {
    context?: string;
    limit?: number;
}

export interface SaveConversationMessageRequest {
    id: string;
    saveMessageRequest: SaveMessageRequest;
}

export interface UpdateConversationOperationRequest {
    id: string;
    updateConversationRequest: UpdateConversationRequest;
}

export interface UpdateConversationMessageMetadataRequest {
    id: string;
    updateMessageMetadataRequest: UpdateMessageMetadataRequest;
}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConversation without sending the request
     */
    async createConversationRequestOpts(requestParameters: CreateConversationOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConversationRequestToJSON(requestParameters['createConversationRequest']),
        };
    }

    /**
     * Persist a new LLM conversation.
     */
    async createConversationRaw(requestParameters: CreateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.createConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Persist a new LLM conversation.
     */
    async createConversation(requestParameters: CreateConversationOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.createConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConversation without sending the request
     */
    async deleteConversationRequestOpts(requestParameters: DeleteConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Soft-delete a conversation.
     */
    async deleteConversationRaw(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft-delete a conversation.
     */
    async deleteConversation(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConversation without sending the request
     */
    async getConversationRequestOpts(requestParameters: GetConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch one conversation.
     */
    async getConversationRaw(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.getConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Fetch one conversation.
     */
    async getConversation(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.getConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLatestConversationForContext without sending the request
     */
    async getLatestConversationForContextRequestOpts(requestParameters: GetLatestConversationForContextRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['context'] == null) {
            throw new runtime.RequiredError(
                'context',
                'Required parameter "context" was null or undefined when calling getLatestConversationForContext().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['context'] != null) {
            queryParameters['context'] = requestParameters['context'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/latest`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the most recently active conversation for a given context tag.
     */
    async getLatestConversationForContextRaw(requestParameters: GetLatestConversationForContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.getLatestConversationForContextRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Fetch the most recently active conversation for a given context tag.
     */
    async getLatestConversationForContext(requestParameters: GetLatestConversationForContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.getLatestConversationForContextRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversationMessages without sending the request
     */
    async listConversationMessagesRequestOpts(requestParameters: ListConversationMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listConversationMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['before'] != null) {
            queryParameters['before'] = requestParameters['before'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}/messages`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List messages in a conversation.
     */
    async listConversationMessagesRaw(requestParameters: ListConversationMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConversationMessage>>> {
        const requestOptions = await this.listConversationMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConversationMessageFromJSON));
    }

    /**
     * List messages in a conversation.
     */
    async listConversationMessages(requestParameters: ListConversationMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConversationMessage>> {
        const response = await this.listConversationMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversations without sending the request
     */
    async listConversationsRequestOpts(requestParameters: ListConversationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['context'] != null) {
            queryParameters['context'] = requestParameters['context'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the caller\'s persisted LLM conversations.
     */
    async listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Conversation>>> {
        const requestOptions = await this.listConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConversationFromJSON));
    }

    /**
     * List the caller\'s persisted LLM conversations.
     */
    async listConversations(requestParameters: ListConversationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Conversation>> {
        const response = await this.listConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for saveConversationMessage without sending the request
     */
    async saveConversationMessageRequestOpts(requestParameters: SaveConversationMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling saveConversationMessage().'
            );
        }

        if (requestParameters['saveMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'saveMessageRequest',
                'Required parameter "saveMessageRequest" was null or undefined when calling saveConversationMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}/messages`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveMessageRequestToJSON(requestParameters['saveMessageRequest']),
        };
    }

    /**
     * Append a message to a conversation.
     */
    async saveConversationMessageRaw(requestParameters: SaveConversationMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationMessage>> {
        const requestOptions = await this.saveConversationMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationMessageFromJSON(jsonValue));
    }

    /**
     * Append a message to a conversation.
     */
    async saveConversationMessage(requestParameters: SaveConversationMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationMessage> {
        const response = await this.saveConversationMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConversation without sending the request
     */
    async updateConversationRequestOpts(requestParameters: UpdateConversationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateConversation().'
            );
        }

        if (requestParameters['updateConversationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateConversationRequest',
                'Required parameter "updateConversationRequest" was null or undefined when calling updateConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateConversationRequestToJSON(requestParameters['updateConversationRequest']),
        };
    }

    /**
     * Update conversation metadata (title, context, cwd, session_id, pinned).
     */
    async updateConversationRaw(requestParameters: UpdateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.updateConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Update conversation metadata (title, context, cwd, session_id, pinned).
     */
    async updateConversation(requestParameters: UpdateConversationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.updateConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConversationMessageMetadata without sending the request
     */
    async updateConversationMessageMetadataRequestOpts(requestParameters: UpdateConversationMessageMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateConversationMessageMetadata().'
            );
        }

        if (requestParameters['updateMessageMetadataRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMessageMetadataRequest',
                'Required parameter "updateMessageMetadataRequest" was null or undefined when calling updateConversationMessageMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/conversations/{id}/messages`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMessageMetadataRequestToJSON(requestParameters['updateMessageMetadataRequest']),
        };
    }

    /**
     * Patch metadata on an existing message. Body must include the message id (path is the conversation id, not the message). 
     */
    async updateConversationMessageMetadataRaw(requestParameters: UpdateConversationMessageMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationMessage>> {
        const requestOptions = await this.updateConversationMessageMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationMessageFromJSON(jsonValue));
    }

    /**
     * Patch metadata on an existing message. Body must include the message id (path is the conversation id, not the message). 
     */
    async updateConversationMessageMetadata(requestParameters: UpdateConversationMessageMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationMessage> {
        const response = await this.updateConversationMessageMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
