/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptOrganizationInvitationRequest,
    AcceptOrganizationInvitationRequestFromJSON,
    AcceptOrganizationInvitationRequestToJSON,
} from '../models/AcceptOrganizationInvitationRequest';
import {
    type AddOrganizationMemberRequest,
    AddOrganizationMemberRequestFromJSON,
    AddOrganizationMemberRequestToJSON,
} from '../models/AddOrganizationMemberRequest';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateOrganizationInvitationRequest,
    CreateOrganizationInvitationRequestFromJSON,
    CreateOrganizationInvitationRequestToJSON,
} from '../models/CreateOrganizationInvitationRequest';
import {
    type CreateOrganizationRequest,
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
} from '../models/CreateOrganizationRequest';
import {
    type CreateWorkspaceRequest,
    CreateWorkspaceRequestFromJSON,
    CreateWorkspaceRequestToJSON,
} from '../models/CreateWorkspaceRequest';
import {
    type OrganizationDetailLegacy,
    OrganizationDetailLegacyFromJSON,
    OrganizationDetailLegacyToJSON,
} from '../models/OrganizationDetailLegacy';
import {
    type OrganizationInvitation,
    OrganizationInvitationFromJSON,
    OrganizationInvitationToJSON,
} from '../models/OrganizationInvitation';
import {
    type OrganizationInvitationListResponse,
    OrganizationInvitationListResponseFromJSON,
    OrganizationInvitationListResponseToJSON,
} from '../models/OrganizationInvitationListResponse';
import {
    type OrganizationListResponse,
    OrganizationListResponseFromJSON,
    OrganizationListResponseToJSON,
} from '../models/OrganizationListResponse';
import {
    type OrganizationMemberListResponse,
    OrganizationMemberListResponseFromJSON,
    OrganizationMemberListResponseToJSON,
} from '../models/OrganizationMemberListResponse';
import {
    type UpdateOrganizationMemberRequest,
    UpdateOrganizationMemberRequestFromJSON,
    UpdateOrganizationMemberRequestToJSON,
} from '../models/UpdateOrganizationMemberRequest';
import {
    type UpdateOrganizationRequest,
    UpdateOrganizationRequestFromJSON,
    UpdateOrganizationRequestToJSON,
} from '../models/UpdateOrganizationRequest';
import {
    type WorkspaceEnvelope,
    WorkspaceEnvelopeFromJSON,
    WorkspaceEnvelopeToJSON,
} from '../models/WorkspaceEnvelope';
import {
    type WorkspaceListResponse,
    WorkspaceListResponseFromJSON,
    WorkspaceListResponseToJSON,
} from '../models/WorkspaceListResponse';

export interface AcceptOrganizationInvitationOperationRequest {
    org: string;
    acceptOrganizationInvitationRequest: AcceptOrganizationInvitationRequest;
}

export interface AddOrganizationMemberOperationRequest {
    org: string;
    addOrganizationMemberRequest: AddOrganizationMemberRequest;
}

export interface CreateOrganizationOperationRequest {
    createOrganizationRequest: CreateOrganizationRequest;
}

export interface CreateOrganizationConceptRequest {
    org: string;
    requestBody: { [key: string]: any; };
}

export interface CreateOrganizationCustomRoleRequest {
    org: string;
    requestBody: { [key: string]: any; };
}

export interface CreateOrganizationInvitationOperationRequest {
    org: string;
    createOrganizationInvitationRequest: CreateOrganizationInvitationRequest;
}

export interface CreateOrganizationWorkspaceRequest {
    org: string;
    createWorkspaceRequest: CreateWorkspaceRequest;
}

export interface DeleteOrganizationRequest {
    org: string;
}

export interface DeleteOrganizationConceptRequest {
    org: string;
    slug: string;
}

export interface DeleteOrganizationCustomRoleRequest {
    org: string;
    roleId: string;
}

export interface DeleteOrganizationLogoRequest {
    org: string;
}

export interface GetOrganizationRequest {
    org: string;
}

export interface GetOrganizationConceptRequest {
    org: string;
    slug: string;
}

export interface ListOrganizationAuditLogRequest {
    org: string;
    limit?: number;
    cursor?: string;
}

export interface ListOrganizationConceptsRequest {
    org: string;
}

export interface ListOrganizationCustomRolesRequest {
    org: string;
}

export interface ListOrganizationInvitationsRequest {
    org: string;
}

export interface ListOrganizationMembersRequest {
    org: string;
}

export interface ListOrganizationWorkspacesRequest {
    org: string;
}

export interface RemoveOrganizationMemberRequest {
    org: string;
    memberId: string;
}

export interface ResendOrganizationInvitationRequest {
    org: string;
    invitationId: string;
}

export interface RevokeOrganizationInvitationRequest {
    org: string;
    invitationId: string;
}

export interface UpdateOrganizationOperationRequest {
    org: string;
    updateOrganizationRequest: UpdateOrganizationRequest;
}

export interface UpdateOrganizationConceptRequest {
    org: string;
    slug: string;
    requestBody: { [key: string]: any; };
}

export interface UpdateOrganizationCustomRoleRequest {
    org: string;
    roleId: string;
    requestBody: { [key: string]: any; };
}

export interface UpdateOrganizationMemberOperationRequest {
    org: string;
    memberId: string;
    updateOrganizationMemberRequest: UpdateOrganizationMemberRequest;
}

export interface UploadOrganizationLogoRequest {
    org: string;
    file?: Blob;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptOrganizationInvitation without sending the request
     */
    async acceptOrganizationInvitationRequestOpts(requestParameters: AcceptOrganizationInvitationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling acceptOrganizationInvitation().'
            );
        }

        if (requestParameters['acceptOrganizationInvitationRequest'] == null) {
            throw new runtime.RequiredError(
                'acceptOrganizationInvitationRequest',
                'Required parameter "acceptOrganizationInvitationRequest" was null or undefined when calling acceptOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/accept-invitation`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptOrganizationInvitationRequestToJSON(requestParameters['acceptOrganizationInvitationRequest']),
        };
    }

    /**
     * Accept an invitation to this organization.
     */
    async acceptOrganizationInvitationRaw(requestParameters: AcceptOrganizationInvitationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.acceptOrganizationInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Accept an invitation to this organization.
     */
    async acceptOrganizationInvitation(requestParameters: AcceptOrganizationInvitationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.acceptOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addOrganizationMember without sending the request
     */
    async addOrganizationMemberRequestOpts(requestParameters: AddOrganizationMemberOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling addOrganizationMember().'
            );
        }

        if (requestParameters['addOrganizationMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'addOrganizationMemberRequest',
                'Required parameter "addOrganizationMemberRequest" was null or undefined when calling addOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/members`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddOrganizationMemberRequestToJSON(requestParameters['addOrganizationMemberRequest']),
        };
    }

    /**
     * Add a member directly (skips invitation flow).
     */
    async addOrganizationMemberRaw(requestParameters: AddOrganizationMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.addOrganizationMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add a member directly (skips invitation flow).
     */
    async addOrganizationMember(requestParameters: AddOrganizationMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.addOrganizationMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrganization without sending the request
     */
    async createOrganizationRequestOpts(requestParameters: CreateOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationRequest',
                'Required parameter "createOrganizationRequest" was null or undefined when calling createOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        };
    }

    /**
     * Create an organization.
     */
    async createOrganizationRaw(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.createOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create an organization.
     */
    async createOrganization(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrganizationConcept without sending the request
     */
    async createOrganizationConceptRequestOpts(requestParameters: CreateOrganizationConceptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling createOrganizationConcept().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling createOrganizationConcept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/concepts`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Create an org-brain concept (admin+ only).
     */
    async createOrganizationConceptRaw(requestParameters: CreateOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.createOrganizationConceptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create an org-brain concept (admin+ only).
     */
    async createOrganizationConcept(requestParameters: CreateOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createOrganizationConceptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrganizationCustomRole without sending the request
     */
    async createOrganizationCustomRoleRequestOpts(requestParameters: CreateOrganizationCustomRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling createOrganizationCustomRole().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling createOrganizationCustomRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/roles`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Create a custom role (admin+ only).
     */
    async createOrganizationCustomRoleRaw(requestParameters: CreateOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.createOrganizationCustomRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a custom role (admin+ only).
     */
    async createOrganizationCustomRole(requestParameters: CreateOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createOrganizationCustomRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrganizationInvitation without sending the request
     */
    async createOrganizationInvitationRequestOpts(requestParameters: CreateOrganizationInvitationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling createOrganizationInvitation().'
            );
        }

        if (requestParameters['createOrganizationInvitationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationInvitationRequest',
                'Required parameter "createOrganizationInvitationRequest" was null or undefined when calling createOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/invitations`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationInvitationRequestToJSON(requestParameters['createOrganizationInvitationRequest']),
        };
    }

    /**
     * Pending invitations count toward seat cap. Free-tier callers at the cap receive a `402` with billing-upgrade payload; paid-tier auto-scales the Stripe quantity. 
     * Invite a user to the organization.
     */
    async createOrganizationInvitationRaw(requestParameters: CreateOrganizationInvitationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationInvitation>> {
        const requestOptions = await this.createOrganizationInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationInvitationFromJSON(jsonValue));
    }

    /**
     * Pending invitations count toward seat cap. Free-tier callers at the cap receive a `402` with billing-upgrade payload; paid-tier auto-scales the Stripe quantity. 
     * Invite a user to the organization.
     */
    async createOrganizationInvitation(requestParameters: CreateOrganizationInvitationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationInvitation> {
        const response = await this.createOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrganizationWorkspace without sending the request
     */
    async createOrganizationWorkspaceRequestOpts(requestParameters: CreateOrganizationWorkspaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling createOrganizationWorkspace().'
            );
        }

        if (requestParameters['createWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkspaceRequest',
                'Required parameter "createWorkspaceRequest" was null or undefined when calling createOrganizationWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkspaceRequestToJSON(requestParameters['createWorkspaceRequest']),
        };
    }

    /**
     * Requires the `OrgActionCreateWorkspace` action permission. Slug collisions auto-suffix (`-2`, `-3`, ...). 
     * Create a workspace inside an organization.
     */
    async createOrganizationWorkspaceRaw(requestParameters: CreateOrganizationWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceEnvelope>> {
        const requestOptions = await this.createOrganizationWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceEnvelopeFromJSON(jsonValue));
    }

    /**
     * Requires the `OrgActionCreateWorkspace` action permission. Slug collisions auto-suffix (`-2`, `-3`, ...). 
     * Create a workspace inside an organization.
     */
    async createOrganizationWorkspace(requestParameters: CreateOrganizationWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceEnvelope> {
        const response = await this.createOrganizationWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteOrganization without sending the request
     */
    async deleteOrganizationRequestOpts(requestParameters: DeleteOrganizationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling deleteOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an organization.
     */
    async deleteOrganizationRaw(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an organization.
     */
    async deleteOrganization(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteOrganizationConcept without sending the request
     */
    async deleteOrganizationConceptRequestOpts(requestParameters: DeleteOrganizationConceptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling deleteOrganizationConcept().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling deleteOrganizationConcept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/concepts/{slug}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a concept (admin+ only).
     */
    async deleteOrganizationConceptRaw(requestParameters: DeleteOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrganizationConceptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a concept (admin+ only).
     */
    async deleteOrganizationConcept(requestParameters: DeleteOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationConceptRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteOrganizationCustomRole without sending the request
     */
    async deleteOrganizationCustomRoleRequestOpts(requestParameters: DeleteOrganizationCustomRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling deleteOrganizationCustomRole().'
            );
        }

        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling deleteOrganizationCustomRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/roles/{roleId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{roleId}', encodeURIComponent(String(requestParameters['roleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a custom role (admin+ only).
     */
    async deleteOrganizationCustomRoleRaw(requestParameters: DeleteOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrganizationCustomRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a custom role (admin+ only).
     */
    async deleteOrganizationCustomRole(requestParameters: DeleteOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationCustomRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteOrganizationLogo without sending the request
     */
    async deleteOrganizationLogoRequestOpts(requestParameters: DeleteOrganizationLogoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling deleteOrganizationLogo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/logo`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the organization logo.
     */
    async deleteOrganizationLogoRaw(requestParameters: DeleteOrganizationLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrganizationLogoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete the organization logo.
     */
    async deleteOrganizationLogo(requestParameters: DeleteOrganizationLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationLogoRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getOrganization without sending the request
     */
    async getOrganizationRequestOpts(requestParameters: GetOrganizationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling getOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Wire format note:** response uses PascalCase keys (`ID`, `Name`, `Slug`, ...) — distinct from the rest of the SpatioAPI\'s camelCase convention. Documented as-is; a future cleanup will harmonize. 
     * Fetch a single organization.
     */
    async getOrganizationRaw(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationDetailLegacy>> {
        const requestOptions = await this.getOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationDetailLegacyFromJSON(jsonValue));
    }

    /**
     * **Wire format note:** response uses PascalCase keys (`ID`, `Name`, `Slug`, ...) — distinct from the rest of the SpatioAPI\'s camelCase convention. Documented as-is; a future cleanup will harmonize. 
     * Fetch a single organization.
     */
    async getOrganization(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationDetailLegacy> {
        const response = await this.getOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationConcept without sending the request
     */
    async getOrganizationConceptRequestOpts(requestParameters: GetOrganizationConceptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling getOrganizationConcept().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getOrganizationConcept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/concepts/{slug}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a concept.
     */
    async getOrganizationConceptRaw(requestParameters: GetOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.getOrganizationConceptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Fetch a concept.
     */
    async getOrganizationConcept(requestParameters: GetOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getOrganizationConceptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMyOrganizations without sending the request
     */
    async listMyOrganizationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the caller\'s organizations.
     */
    async listMyOrganizationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationListResponse>> {
        const requestOptions = await this.listMyOrganizationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationListResponseFromJSON(jsonValue));
    }

    /**
     * List the caller\'s organizations.
     */
    async listMyOrganizations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationListResponse> {
        const response = await this.listMyOrganizationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationAuditLog without sending the request
     */
    async listOrganizationAuditLogRequestOpts(requestParameters: ListOrganizationAuditLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationAuditLog().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/audit-log`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read the organization audit log (admin / billing-admin only).
     */
    async listOrganizationAuditLogRaw(requestParameters: ListOrganizationAuditLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.listOrganizationAuditLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Read the organization audit log (admin / billing-admin only).
     */
    async listOrganizationAuditLog(requestParameters: ListOrganizationAuditLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.listOrganizationAuditLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationConcepts without sending the request
     */
    async listOrganizationConceptsRequestOpts(requestParameters: ListOrganizationConceptsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationConcepts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/concepts`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List org-brain concepts (curated knowledge surfaced to agents).
     */
    async listOrganizationConceptsRaw(requestParameters: ListOrganizationConceptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.listOrganizationConceptsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List org-brain concepts (curated knowledge surfaced to agents).
     */
    async listOrganizationConcepts(requestParameters: ListOrganizationConceptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.listOrganizationConceptsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationCustomRoles without sending the request
     */
    async listOrganizationCustomRolesRequestOpts(requestParameters: ListOrganizationCustomRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationCustomRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/roles`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List custom roles defined on the organization.
     */
    async listOrganizationCustomRolesRaw(requestParameters: ListOrganizationCustomRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.listOrganizationCustomRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List custom roles defined on the organization.
     */
    async listOrganizationCustomRoles(requestParameters: ListOrganizationCustomRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.listOrganizationCustomRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationInvitations without sending the request
     */
    async listOrganizationInvitationsRequestOpts(requestParameters: ListOrganizationInvitationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationInvitations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/invitations`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List pending invitations for an organization.
     */
    async listOrganizationInvitationsRaw(requestParameters: ListOrganizationInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationInvitationListResponse>> {
        const requestOptions = await this.listOrganizationInvitationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationInvitationListResponseFromJSON(jsonValue));
    }

    /**
     * List pending invitations for an organization.
     */
    async listOrganizationInvitations(requestParameters: ListOrganizationInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationInvitationListResponse> {
        const response = await this.listOrganizationInvitationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationMembers without sending the request
     */
    async listOrganizationMembersRequestOpts(requestParameters: ListOrganizationMembersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/members`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List members of an organization.
     */
    async listOrganizationMembersRaw(requestParameters: ListOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationMemberListResponse>> {
        const requestOptions = await this.listOrganizationMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationMemberListResponseFromJSON(jsonValue));
    }

    /**
     * List members of an organization.
     */
    async listOrganizationMembers(requestParameters: ListOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationMemberListResponse> {
        const response = await this.listOrganizationMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationWorkspaces without sending the request
     */
    async listOrganizationWorkspacesRequestOpts(requestParameters: ListOrganizationWorkspacesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling listOrganizationWorkspaces().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/workspaces`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List workspaces in an organization.
     */
    async listOrganizationWorkspacesRaw(requestParameters: ListOrganizationWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceListResponse>> {
        const requestOptions = await this.listOrganizationWorkspacesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceListResponseFromJSON(jsonValue));
    }

    /**
     * List workspaces in an organization.
     */
    async listOrganizationWorkspaces(requestParameters: ListOrganizationWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceListResponse> {
        const response = await this.listOrganizationWorkspacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeOrganizationMember without sending the request
     */
    async removeOrganizationMemberRequestOpts(requestParameters: RemoveOrganizationMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling removeOrganizationMember().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling removeOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/members/{memberId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a member from the organization.
     */
    async removeOrganizationMemberRaw(requestParameters: RemoveOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeOrganizationMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a member from the organization.
     */
    async removeOrganizationMember(requestParameters: RemoveOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeOrganizationMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for resendOrganizationInvitation without sending the request
     */
    async resendOrganizationInvitationRequestOpts(requestParameters: ResendOrganizationInvitationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling resendOrganizationInvitation().'
            );
        }

        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling resendOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/invitations/{invitationId}/resend`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{invitationId}', encodeURIComponent(String(requestParameters['invitationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke and reissue an invitation with a fresh token.
     */
    async resendOrganizationInvitationRaw(requestParameters: ResendOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationInvitation>> {
        const requestOptions = await this.resendOrganizationInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationInvitationFromJSON(jsonValue));
    }

    /**
     * Revoke and reissue an invitation with a fresh token.
     */
    async resendOrganizationInvitation(requestParameters: ResendOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationInvitation> {
        const response = await this.resendOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeOrganizationInvitation without sending the request
     */
    async revokeOrganizationInvitationRequestOpts(requestParameters: RevokeOrganizationInvitationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling revokeOrganizationInvitation().'
            );
        }

        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling revokeOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/invitations/{invitationId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{invitationId}', encodeURIComponent(String(requestParameters['invitationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a pending invitation.
     */
    async revokeOrganizationInvitationRaw(requestParameters: RevokeOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeOrganizationInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a pending invitation.
     */
    async revokeOrganizationInvitation(requestParameters: RevokeOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeOrganizationInvitationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateOrganization without sending the request
     */
    async updateOrganizationRequestOpts(requestParameters: UpdateOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling updateOrganization().'
            );
        }

        if (requestParameters['updateOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationRequest',
                'Required parameter "updateOrganizationRequest" was null or undefined when calling updateOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationRequestToJSON(requestParameters['updateOrganizationRequest']),
        };
    }

    /**
     * Update organization metadata.
     */
    async updateOrganizationRaw(requestParameters: UpdateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.updateOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update organization metadata.
     */
    async updateOrganization(requestParameters: UpdateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOrganizationConcept without sending the request
     */
    async updateOrganizationConceptRequestOpts(requestParameters: UpdateOrganizationConceptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling updateOrganizationConcept().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling updateOrganizationConcept().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateOrganizationConcept().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/concepts/{slug}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Update a concept (admin+ only).
     */
    async updateOrganizationConceptRaw(requestParameters: UpdateOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.updateOrganizationConceptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update a concept (admin+ only).
     */
    async updateOrganizationConcept(requestParameters: UpdateOrganizationConceptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateOrganizationConceptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOrganizationCustomRole without sending the request
     */
    async updateOrganizationCustomRoleRequestOpts(requestParameters: UpdateOrganizationCustomRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling updateOrganizationCustomRole().'
            );
        }

        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling updateOrganizationCustomRole().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateOrganizationCustomRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/roles/{roleId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{roleId}', encodeURIComponent(String(requestParameters['roleId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Update a custom role (admin+ only).
     */
    async updateOrganizationCustomRoleRaw(requestParameters: UpdateOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.updateOrganizationCustomRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update a custom role (admin+ only).
     */
    async updateOrganizationCustomRole(requestParameters: UpdateOrganizationCustomRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateOrganizationCustomRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOrganizationMember without sending the request
     */
    async updateOrganizationMemberRequestOpts(requestParameters: UpdateOrganizationMemberOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling updateOrganizationMember().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling updateOrganizationMember().'
            );
        }

        if (requestParameters['updateOrganizationMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationMemberRequest',
                'Required parameter "updateOrganizationMemberRequest" was null or undefined when calling updateOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/organizations/{org}/members/{memberId}`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationMemberRequestToJSON(requestParameters['updateOrganizationMemberRequest']),
        };
    }

    /**
     * Update a member\'s role.
     */
    async updateOrganizationMemberRaw(requestParameters: UpdateOrganizationMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.updateOrganizationMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update a member\'s role.
     */
    async updateOrganizationMember(requestParameters: UpdateOrganizationMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateOrganizationMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadOrganizationLogo without sending the request
     */
    async uploadOrganizationLogoRequestOpts(requestParameters: UploadOrganizationLogoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['org'] == null) {
            throw new runtime.RequiredError(
                'org',
                'Required parameter "org" was null or undefined when calling uploadOrganizationLogo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/v1/organizations/{org}/logo`;
        urlPath = urlPath.replace('{org}', encodeURIComponent(String(requestParameters['org'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload (or replace) the organization logo. Multipart.
     */
    async uploadOrganizationLogoRaw(requestParameters: UploadOrganizationLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.uploadOrganizationLogoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Upload (or replace) the organization logo. Multipart.
     */
    async uploadOrganizationLogo(requestParameters: UploadOrganizationLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.uploadOrganizationLogoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
