/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type Cell,
    CellFromJSON,
    CellToJSON,
} from '../models/Cell';
import {
    type CreateNote400Response,
    CreateNote400ResponseFromJSON,
    CreateNote400ResponseToJSON,
} from '../models/CreateNote400Response';
import {
    type CreateRowRequest,
    CreateRowRequestFromJSON,
    CreateRowRequestToJSON,
} from '../models/CreateRowRequest';
import {
    type CreateSheetRequest,
    CreateSheetRequestFromJSON,
    CreateSheetRequestToJSON,
} from '../models/CreateSheetRequest';
import {
    type Row,
    RowFromJSON,
    RowToJSON,
} from '../models/Row';
import {
    type RowList,
    RowListFromJSON,
    RowListToJSON,
} from '../models/RowList';
import {
    type Sheet,
    SheetFromJSON,
    SheetToJSON,
} from '../models/Sheet';
import {
    type SheetListEnvelope,
    SheetListEnvelopeFromJSON,
    SheetListEnvelopeToJSON,
} from '../models/SheetListEnvelope';
import {
    type SuccessFlag,
    SuccessFlagFromJSON,
    SuccessFlagToJSON,
} from '../models/SuccessFlag';
import {
    type UpdateCellRequest,
    UpdateCellRequestFromJSON,
    UpdateCellRequestToJSON,
} from '../models/UpdateCellRequest';
import {
    type UpdateRowRequest,
    UpdateRowRequestFromJSON,
    UpdateRowRequestToJSON,
} from '../models/UpdateRowRequest';
import {
    type UpdateSheetRequest,
    UpdateSheetRequestFromJSON,
    UpdateSheetRequestToJSON,
} from '../models/UpdateSheetRequest';

export interface CreateSheetOperationRequest {
    createSheetRequest: CreateSheetRequest;
    accountId?: string;
    provider?: string;
    xWorkspaceID?: string;
}

export interface CreateSheetRowRequest {
    id: string;
    createRowRequest: CreateRowRequest;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface DeleteSheetRequest {
    id: string;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface DeleteSheetRowRequest {
    id: string;
    rowIndex: number;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface GetSheetRequest {
    id: string;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface ListSheetRowsRequest {
    id: string;
    accountId?: string;
    xWorkspaceID?: string;
    limit?: number;
    offset?: number;
}

export interface ListSheetsRequest {
    accountId?: string;
    provider?: string;
    xWorkspaceID?: string;
    limit?: number;
    offset?: number;
}

export interface UpdateSheetOperationRequest {
    id: string;
    updateSheetRequest: UpdateSheetRequest;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface UpdateSheetCellRequest {
    id: string;
    rowIndex: number;
    column: string;
    updateCellRequest: UpdateCellRequest;
    accountId?: string;
    xWorkspaceID?: string;
}

export interface UpdateSheetRowRequest {
    id: string;
    rowIndex: number;
    updateRowRequest: UpdateRowRequest;
    accountId?: string;
    xWorkspaceID?: string;
}

/**
 * 
 */
export class SheetsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSheet without sending the request
     */
    async createSheetRequestOpts(requestParameters: CreateSheetOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSheetRequest'] == null) {
            throw new runtime.RequiredError(
                'createSheetRequest',
                'Required parameter "createSheetRequest" was null or undefined when calling createSheet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSheetRequestToJSON(requestParameters['createSheetRequest']),
        };
    }

    /**
     * Creates a new sheet under the target account. Target resolution mirrors `POST /v1/notes`: body `accountId` → `?accountId=` → body `provider` → `?provider=` → caller\'s single connected account (errors with `ambiguous_account` if more than one is connected and no selector is supplied). 
     * Create a sheet.
     */
    async createSheetRaw(requestParameters: CreateSheetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sheet>> {
        const requestOptions = await this.createSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetFromJSON(jsonValue));
    }

    /**
     * Creates a new sheet under the target account. Target resolution mirrors `POST /v1/notes`: body `accountId` → `?accountId=` → body `provider` → `?provider=` → caller\'s single connected account (errors with `ambiguous_account` if more than one is connected and no selector is supplied). 
     * Create a sheet.
     */
    async createSheet(requestParameters: CreateSheetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sheet> {
        const response = await this.createSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSheetRow without sending the request
     */
    async createSheetRowRequestOpts(requestParameters: CreateSheetRowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createSheetRow().'
            );
        }

        if (requestParameters['createRowRequest'] == null) {
            throw new runtime.RequiredError(
                'createRowRequest',
                'Required parameter "createRowRequest" was null or undefined when calling createSheetRow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}/rows`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRowRequestToJSON(requestParameters['createRowRequest']),
        };
    }

    /**
     * Inserts a row at `index` (zero-based) or appends to the end when `index` is omitted. 
     * Insert a row.
     */
    async createSheetRowRaw(requestParameters: CreateSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Row>> {
        const requestOptions = await this.createSheetRowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RowFromJSON(jsonValue));
    }

    /**
     * Inserts a row at `index` (zero-based) or appends to the end when `index` is omitted. 
     * Insert a row.
     */
    async createSheetRow(requestParameters: CreateSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Row> {
        const response = await this.createSheetRowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSheet without sending the request
     */
    async deleteSheetRequestOpts(requestParameters: DeleteSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSheet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a sheet.
     */
    async deleteSheetRaw(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessFlag>> {
        const requestOptions = await this.deleteSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFlagFromJSON(jsonValue));
    }

    /**
     * Delete a sheet.
     */
    async deleteSheet(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessFlag> {
        const response = await this.deleteSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSheetRow without sending the request
     */
    async deleteSheetRowRequestOpts(requestParameters: DeleteSheetRowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSheetRow().'
            );
        }

        if (requestParameters['rowIndex'] == null) {
            throw new runtime.RequiredError(
                'rowIndex',
                'Required parameter "rowIndex" was null or undefined when calling deleteSheetRow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}/rows/{rowIndex}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{rowIndex}', encodeURIComponent(String(requestParameters['rowIndex'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a row.
     */
    async deleteSheetRowRaw(requestParameters: DeleteSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessFlag>> {
        const requestOptions = await this.deleteSheetRowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFlagFromJSON(jsonValue));
    }

    /**
     * Delete a row.
     */
    async deleteSheetRow(requestParameters: DeleteSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessFlag> {
        const response = await this.deleteSheetRowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSheet without sending the request
     */
    async getSheetRequestOpts(requestParameters: GetSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSheet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch one sheet.
     */
    async getSheetRaw(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sheet>> {
        const requestOptions = await this.getSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetFromJSON(jsonValue));
    }

    /**
     * Fetch one sheet.
     */
    async getSheet(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sheet> {
        const response = await this.getSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSheetRows without sending the request
     */
    async listSheetRowsRequestOpts(requestParameters: ListSheetRowsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listSheetRows().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}/rows`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Single-account row list. Unlike `GET /v1/sheets`, row listing always targets the one account that owns the sheet, so the response is a plain `{ rows, total }` rather than a fan-out envelope. 
     * List rows in a sheet.
     */
    async listSheetRowsRaw(requestParameters: ListSheetRowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RowList>> {
        const requestOptions = await this.listSheetRowsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RowListFromJSON(jsonValue));
    }

    /**
     * Single-account row list. Unlike `GET /v1/sheets`, row listing always targets the one account that owns the sheet, so the response is a plain `{ rows, total }` rather than a fan-out envelope. 
     * List rows in a sheet.
     */
    async listSheetRows(requestParameters: ListSheetRowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RowList> {
        const response = await this.listSheetRowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSheets without sending the request
     */
    async listSheetsRequestOpts(requestParameters: ListSheetsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fan-out list. Returns every sheet visible to the caller across every connected sheets provider, paginated by `limit` / `offset`. Pass `?accountId=` or `?provider=` to scope to a single source. 
     * List sheets across connected accounts.
     */
    async listSheetsRaw(requestParameters: ListSheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetListEnvelope>> {
        const requestOptions = await this.listSheetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetListEnvelopeFromJSON(jsonValue));
    }

    /**
     * Fan-out list. Returns every sheet visible to the caller across every connected sheets provider, paginated by `limit` / `offset`. Pass `?accountId=` or `?provider=` to scope to a single source. 
     * List sheets across connected accounts.
     */
    async listSheets(requestParameters: ListSheetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetListEnvelope> {
        const response = await this.listSheetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSheet without sending the request
     */
    async updateSheetRequestOpts(requestParameters: UpdateSheetOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSheet().'
            );
        }

        if (requestParameters['updateSheetRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSheetRequest',
                'Required parameter "updateSheetRequest" was null or undefined when calling updateSheet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSheetRequestToJSON(requestParameters['updateSheetRequest']),
        };
    }

    /**
     * Partial update of sheet metadata. The renderer also calls this via `PUT /v1/sheets/{id}` for autosave parity; both verbs invoke the same handler. Per-cell and per-row mutations live on their dedicated endpoints, not here. 
     * Update a sheet (partial).
     */
    async updateSheetRaw(requestParameters: UpdateSheetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sheet>> {
        const requestOptions = await this.updateSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetFromJSON(jsonValue));
    }

    /**
     * Partial update of sheet metadata. The renderer also calls this via `PUT /v1/sheets/{id}` for autosave parity; both verbs invoke the same handler. Per-cell and per-row mutations live on their dedicated endpoints, not here. 
     * Update a sheet (partial).
     */
    async updateSheet(requestParameters: UpdateSheetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sheet> {
        const response = await this.updateSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSheetCell without sending the request
     */
    async updateSheetCellRequestOpts(requestParameters: UpdateSheetCellRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSheetCell().'
            );
        }

        if (requestParameters['rowIndex'] == null) {
            throw new runtime.RequiredError(
                'rowIndex',
                'Required parameter "rowIndex" was null or undefined when calling updateSheetCell().'
            );
        }

        if (requestParameters['column'] == null) {
            throw new runtime.RequiredError(
                'column',
                'Required parameter "column" was null or undefined when calling updateSheetCell().'
            );
        }

        if (requestParameters['updateCellRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCellRequest',
                'Required parameter "updateCellRequest" was null or undefined when calling updateSheetCell().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}/rows/{rowIndex}/cells/{column}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{rowIndex}', encodeURIComponent(String(requestParameters['rowIndex'])));
        urlPath = urlPath.replace('{column}', encodeURIComponent(String(requestParameters['column'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCellRequestToJSON(requestParameters['updateCellRequest']),
        };
    }

    /**
     * Update a single cell.
     */
    async updateSheetCellRaw(requestParameters: UpdateSheetCellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Cell>> {
        const requestOptions = await this.updateSheetCellRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CellFromJSON(jsonValue));
    }

    /**
     * Update a single cell.
     */
    async updateSheetCell(requestParameters: UpdateSheetCellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Cell> {
        const response = await this.updateSheetCellRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSheetRow without sending the request
     */
    async updateSheetRowRequestOpts(requestParameters: UpdateSheetRowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSheetRow().'
            );
        }

        if (requestParameters['rowIndex'] == null) {
            throw new runtime.RequiredError(
                'rowIndex',
                'Required parameter "rowIndex" was null or undefined when calling updateSheetRow().'
            );
        }

        if (requestParameters['updateRowRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRowRequest',
                'Required parameter "updateRowRequest" was null or undefined when calling updateSheetRow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWorkspaceID'] != null) {
            headerParameters['X-Workspace-ID'] = String(requestParameters['xWorkspaceID']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sheets/{id}/rows/{rowIndex}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{rowIndex}', encodeURIComponent(String(requestParameters['rowIndex'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRowRequestToJSON(requestParameters['updateRowRequest']),
        };
    }

    /**
     * Sparse update — keys present in `cells` overwrite that column; keys absent are preserved. 
     * Update a row (sparse).
     */
    async updateSheetRowRaw(requestParameters: UpdateSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Row>> {
        const requestOptions = await this.updateSheetRowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RowFromJSON(jsonValue));
    }

    /**
     * Sparse update — keys present in `cells` overwrite that column; keys absent are preserved. 
     * Update a row (sparse).
     */
    async updateSheetRow(requestParameters: UpdateSheetRowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Row> {
        const response = await this.updateSheetRowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
