/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-account failure attached to `AccountStatus.error` inside a fan-out
 * `Envelope`. `code` is machine-readable and stable across releases for
 * the canonical values (`auth_expired`, `rate_limited`, `provider_5xx`,
 * `timeout`); `unknown` is a fallback and should not be relied on.
 * 
 * @export
 * @interface AccountError
 */
export interface AccountError {
    /**
     * 
     * @type {string}
     * @memberof AccountError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AccountError
     */
    message: string;
}

/**
 * Check if a given object implements the AccountError interface.
 */
export function instanceOfAccountError(value: object): value is AccountError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AccountErrorFromJSON(json: any): AccountError {
    return AccountErrorFromJSONTyped(json, false);
}

export function AccountErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function AccountErrorToJSON(json: any): AccountError {
    return AccountErrorToJSONTyped(json, false);
}

export function AccountErrorToJSONTyped(value?: AccountError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

