/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddOrganizationMemberRequest
 */
export interface AddOrganizationMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddOrganizationMemberRequest
     */
    email: string;
    /**
     * 
     * @type {AddOrganizationMemberRequestRoleEnum}
     * @memberof AddOrganizationMemberRequest
     */
    role?: AddOrganizationMemberRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AddOrganizationMemberRequest
     */
    workspaceId?: string;
}


/**
 * @export
 */
export const AddOrganizationMemberRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    BillingAdmin: 'billing_admin',
    Member: 'member'
} as const;
export type AddOrganizationMemberRequestRoleEnum = typeof AddOrganizationMemberRequestRoleEnum[keyof typeof AddOrganizationMemberRequestRoleEnum];


/**
 * Check if a given object implements the AddOrganizationMemberRequest interface.
 */
export function instanceOfAddOrganizationMemberRequest(value: object): value is AddOrganizationMemberRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AddOrganizationMemberRequestFromJSON(json: any): AddOrganizationMemberRequest {
    return AddOrganizationMemberRequestFromJSONTyped(json, false);
}

export function AddOrganizationMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'] == null ? undefined : json['role'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
    };
}

export function AddOrganizationMemberRequestToJSON(json: any): AddOrganizationMemberRequest {
    return AddOrganizationMemberRequestToJSONTyped(json, false);
}

export function AddOrganizationMemberRequestToJSONTyped(value?: AddOrganizationMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
        'workspaceId': value['workspaceId'],
    };
}

