/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddWorkspaceMemberRequest
 */
export interface AddWorkspaceMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddWorkspaceMemberRequest
     */
    email: string;
    /**
     * 
     * @type {AddWorkspaceMemberRequestRoleEnum}
     * @memberof AddWorkspaceMemberRequest
     */
    role: AddWorkspaceMemberRequestRoleEnum;
}


/**
 * @export
 */
export const AddWorkspaceMemberRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member',
    Guest: 'guest'
} as const;
export type AddWorkspaceMemberRequestRoleEnum = typeof AddWorkspaceMemberRequestRoleEnum[keyof typeof AddWorkspaceMemberRequestRoleEnum];


/**
 * Check if a given object implements the AddWorkspaceMemberRequest interface.
 */
export function instanceOfAddWorkspaceMemberRequest(value: object): value is AddWorkspaceMemberRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function AddWorkspaceMemberRequestFromJSON(json: any): AddWorkspaceMemberRequest {
    return AddWorkspaceMemberRequestFromJSONTyped(json, false);
}

export function AddWorkspaceMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWorkspaceMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'],
    };
}

export function AddWorkspaceMemberRequestToJSON(json: any): AddWorkspaceMemberRequest {
    return AddWorkspaceMemberRequestToJSONTyped(json, false);
}

export function AddWorkspaceMemberRequestToJSONTyped(value?: AddWorkspaceMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
    };
}

