/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Agent } from './Agent';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent';

/**
 * 
 * @export
 * @interface AgentListResponse
 */
export interface AgentListResponse {
    /**
     * 
     * @type {Array<Agent>}
     * @memberof AgentListResponse
     */
    agents: Array<Agent> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AgentListResponse
     */
    hasMore?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AgentListResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentListResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the AgentListResponse interface.
 */
export function instanceOfAgentListResponse(value: object): value is AgentListResponse {
    if (!('agents' in value) || value['agents'] === undefined) return false;
    return true;
}

export function AgentListResponseFromJSON(json: any): AgentListResponse {
    return AgentListResponseFromJSONTyped(json, false);
}

export function AgentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agents': (json['agents'] == null ? null : (json['agents'] as Array<any>).map(AgentFromJSON)),
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function AgentListResponseToJSON(json: any): AgentListResponse {
    return AgentListResponseToJSONTyped(json, false);
}

export function AgentListResponseToJSONTyped(value?: AgentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agents': (value['agents'] == null ? null : (value['agents'] as Array<any>).map(AgentToJSON)),
        'hasMore': value['hasMore'],
        'total': value['total'],
        'totalCount': value['totalCount'],
    };
}

