/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error envelope returned by 4xx and 5xx responses across the
 * SpatioAPI. Some endpoints attach extra machine-readable fields
 * (`code`, `accounts`, `requiresPassword`, etc.) — those are documented
 * on the individual operation.
 * 
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * Human-readable error message.
     * @type {string}
     * @memberof ApiError
     */
    error: string;
    /**
     * Machine-readable error code. Stable across releases for the
     * canonical codes (`ambiguous_account`, `no_notes_provider`,
     * `note_not_found`). Absent for generic errors.
     * 
     * @type {string}
     * @memberof ApiError
     */
    code?: string;
}

/**
 * Check if a given object implements the ApiError interface.
 */
export function instanceOfApiError(value: object): value is ApiError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ApiErrorToJSON(json: any): ApiError {
    return ApiErrorToJSONTyped(json, false);
}

export function ApiErrorToJSONTyped(value?: ApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'code': value['code'],
    };
}

