/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkFilesResponseFailedInner } from './BulkFilesResponseFailedInner';
import {
    BulkFilesResponseFailedInnerFromJSON,
    BulkFilesResponseFailedInnerFromJSONTyped,
    BulkFilesResponseFailedInnerToJSON,
    BulkFilesResponseFailedInnerToJSONTyped,
} from './BulkFilesResponseFailedInner';

/**
 * Partial-success envelope for bulk delete/move.
 * @export
 * @interface BulkFilesResponse
 */
export interface BulkFilesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BulkFilesResponse
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof BulkFilesResponse
     */
    affectedCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkFilesResponse
     */
    fileIds: Array<string>;
    /**
     * 
     * @type {Array<BulkFilesResponseFailedInner>}
     * @memberof BulkFilesResponse
     */
    failed: Array<BulkFilesResponseFailedInner>;
}

/**
 * Check if a given object implements the BulkFilesResponse interface.
 */
export function instanceOfBulkFilesResponse(value: object): value is BulkFilesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('affectedCount' in value) || value['affectedCount'] === undefined) return false;
    if (!('fileIds' in value) || value['fileIds'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function BulkFilesResponseFromJSON(json: any): BulkFilesResponse {
    return BulkFilesResponseFromJSONTyped(json, false);
}

export function BulkFilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkFilesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'affectedCount': json['affectedCount'],
        'fileIds': json['fileIds'],
        'failed': ((json['failed'] as Array<any>).map(BulkFilesResponseFailedInnerFromJSON)),
    };
}

export function BulkFilesResponseToJSON(json: any): BulkFilesResponse {
    return BulkFilesResponseToJSONTyped(json, false);
}

export function BulkFilesResponseToJSONTyped(value?: BulkFilesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'affectedCount': value['affectedCount'],
        'fileIds': value['fileIds'],
        'failed': ((value['failed'] as Array<any>).map(BulkFilesResponseFailedInnerToJSON)),
    };
}

