/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkArchiveResponseFailedInner } from './BulkArchiveResponseFailedInner';
import {
    BulkArchiveResponseFailedInnerFromJSON,
    BulkArchiveResponseFailedInnerFromJSONTyped,
    BulkArchiveResponseFailedInnerToJSON,
    BulkArchiveResponseFailedInnerToJSONTyped,
} from './BulkArchiveResponseFailedInner';

/**
 * Partial-success envelope for `bulkArchiveEmails`.
 * @export
 * @interface BulkArchiveResponse
 */
export interface BulkArchiveResponse {
    /**
     * `true` only when zero rows in `failed`.
     * @type {boolean}
     * @memberof BulkArchiveResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkArchiveResponse
     */
    archived: Array<string>;
    /**
     * 
     * @type {Array<BulkArchiveResponseFailedInner>}
     * @memberof BulkArchiveResponse
     */
    failed: Array<BulkArchiveResponseFailedInner>;
}

/**
 * Check if a given object implements the BulkArchiveResponse interface.
 */
export function instanceOfBulkArchiveResponse(value: object): value is BulkArchiveResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function BulkArchiveResponseFromJSON(json: any): BulkArchiveResponse {
    return BulkArchiveResponseFromJSONTyped(json, false);
}

export function BulkArchiveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkArchiveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'archived': json['archived'],
        'failed': ((json['failed'] as Array<any>).map(BulkArchiveResponseFailedInnerFromJSON)),
    };
}

export function BulkArchiveResponseToJSON(json: any): BulkArchiveResponse {
    return BulkArchiveResponseToJSONTyped(json, false);
}

export function BulkArchiveResponseToJSONTyped(value?: BulkArchiveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'archived': value['archived'],
        'failed': ((value['failed'] as Array<any>).map(BulkArchiveResponseFailedInnerToJSON)),
    };
}

