/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Either populate `taskIds` (with optional parallel `accountIds`)
 * for multi-task delete, or `taskId` (with optional `accountId`)
 * for the single-task fallback. `taskIds` wins when both are set.
 * 
 * @export
 * @interface BulkDeleteTasksRequest
 */
export interface BulkDeleteTasksRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkDeleteTasksRequest
     */
    taskIds?: Array<string>;
    /**
     * Parallel slice with taskIds — accountIds[i] targets taskIds[i].
     * @type {Array<string>}
     * @memberof BulkDeleteTasksRequest
     */
    accountIds?: Array<string>;
    /**
     * Singular fallback when only deleting one task.
     * @type {string}
     * @memberof BulkDeleteTasksRequest
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkDeleteTasksRequest
     */
    accountId?: string;
}

/**
 * Check if a given object implements the BulkDeleteTasksRequest interface.
 */
export function instanceOfBulkDeleteTasksRequest(value: object): value is BulkDeleteTasksRequest {
    return true;
}

export function BulkDeleteTasksRequestFromJSON(json: any): BulkDeleteTasksRequest {
    return BulkDeleteTasksRequestFromJSONTyped(json, false);
}

export function BulkDeleteTasksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkDeleteTasksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskIds': json['taskIds'] == null ? undefined : json['taskIds'],
        'accountIds': json['accountIds'] == null ? undefined : json['accountIds'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function BulkDeleteTasksRequestToJSON(json: any): BulkDeleteTasksRequest {
    return BulkDeleteTasksRequestToJSONTyped(json, false);
}

export function BulkDeleteTasksRequestToJSONTyped(value?: BulkDeleteTasksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskIds': value['taskIds'],
        'accountIds': value['accountIds'],
        'taskId': value['taskId'],
        'accountId': value['accountId'],
    };
}

