/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateTaskRequest } from './UpdateTaskRequest';
import {
    UpdateTaskRequestFromJSON,
    UpdateTaskRequestFromJSONTyped,
    UpdateTaskRequestToJSON,
    UpdateTaskRequestToJSONTyped,
} from './UpdateTaskRequest';

/**
 * Apply the same `updates` payload to every id. Same parallel
 * AccountIDs convention as bulk delete.
 * 
 * @export
 * @interface BulkUpdateTasksRequest
 */
export interface BulkUpdateTasksRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkUpdateTasksRequest
     */
    taskIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkUpdateTasksRequest
     */
    accountIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateTasksRequest
     */
    accountId?: string;
    /**
     * 
     * @type {UpdateTaskRequest}
     * @memberof BulkUpdateTasksRequest
     */
    updates: UpdateTaskRequest;
}

/**
 * Check if a given object implements the BulkUpdateTasksRequest interface.
 */
export function instanceOfBulkUpdateTasksRequest(value: object): value is BulkUpdateTasksRequest {
    if (!('taskIds' in value) || value['taskIds'] === undefined) return false;
    if (!('updates' in value) || value['updates'] === undefined) return false;
    return true;
}

export function BulkUpdateTasksRequestFromJSON(json: any): BulkUpdateTasksRequest {
    return BulkUpdateTasksRequestFromJSONTyped(json, false);
}

export function BulkUpdateTasksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateTasksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskIds': json['taskIds'],
        'accountIds': json['accountIds'] == null ? undefined : json['accountIds'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'updates': UpdateTaskRequestFromJSON(json['updates']),
    };
}

export function BulkUpdateTasksRequestToJSON(json: any): BulkUpdateTasksRequest {
    return BulkUpdateTasksRequestToJSONTyped(json, false);
}

export function BulkUpdateTasksRequestToJSONTyped(value?: BulkUpdateTasksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskIds': value['taskIds'],
        'accountIds': value['accountIds'],
        'accountId': value['accountId'],
        'updates': UpdateTaskRequestToJSON(value['updates']),
    };
}

