/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returned by `POST /v1/calendar/sync`. Status code is `202` by
 * default (sync jobs queued); `200` when called with `?wait=true`
 * and all jobs finish within the 10-second polling budget.
 * 
 * @export
 * @interface CalendarSyncResponse
 */
export interface CalendarSyncResponse {
    /**
     * 
     * @type {number}
     * @memberof CalendarSyncResponse
     */
    enqueued: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CalendarSyncResponse
     */
    jobs: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CalendarSyncResponse
     */
    waited?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CalendarSyncResponse
     */
    timed_out?: boolean;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CalendarSyncResponse
     */
    errors?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the CalendarSyncResponse interface.
 */
export function instanceOfCalendarSyncResponse(value: object): value is CalendarSyncResponse {
    if (!('enqueued' in value) || value['enqueued'] === undefined) return false;
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    return true;
}

export function CalendarSyncResponseFromJSON(json: any): CalendarSyncResponse {
    return CalendarSyncResponseFromJSONTyped(json, false);
}

export function CalendarSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarSyncResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enqueued': json['enqueued'],
        'jobs': json['jobs'],
        'waited': json['waited'] == null ? undefined : json['waited'],
        'timed_out': json['timed_out'] == null ? undefined : json['timed_out'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function CalendarSyncResponseToJSON(json: any): CalendarSyncResponse {
    return CalendarSyncResponseToJSONTyped(json, false);
}

export function CalendarSyncResponseToJSONTyped(value?: CalendarSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enqueued': value['enqueued'],
        'jobs': value['jobs'],
        'waited': value['waited'],
        'timed_out': value['timed_out'],
        'errors': value['errors'],
    };
}

