/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CalendarAccountError
 */
export interface CalendarAccountError {
    /**
     * 
     * @type {string}
     * @memberof CalendarAccountError
     */
    account_id: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarAccountError
     */
    account_name: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarAccountError
     */
    error_code: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarAccountError
     */
    error_message: string;
}

/**
 * Check if a given object implements the CalendarAccountError interface.
 */
export function instanceOfCalendarAccountError(value: object): value is CalendarAccountError {
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('account_name' in value) || value['account_name'] === undefined) return false;
    if (!('error_code' in value) || value['error_code'] === undefined) return false;
    if (!('error_message' in value) || value['error_message'] === undefined) return false;
    return true;
}

export function CalendarAccountErrorFromJSON(json: any): CalendarAccountError {
    return CalendarAccountErrorFromJSONTyped(json, false);
}

export function CalendarAccountErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarAccountError {
    if (json == null) {
        return json;
    }
    return {
        
        'account_id': json['account_id'],
        'account_name': json['account_name'],
        'error_code': json['error_code'],
        'error_message': json['error_message'],
    };
}

export function CalendarAccountErrorToJSON(json: any): CalendarAccountError {
    return CalendarAccountErrorToJSONTyped(json, false);
}

export function CalendarAccountErrorToJSONTyped(value?: CalendarAccountError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['account_id'],
        'account_name': value['account_name'],
        'error_code': value['error_code'],
        'error_message': value['error_message'],
    };
}

