/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarProviderInfo } from './CalendarProviderInfo';
import {
    CalendarProviderInfoFromJSON,
    CalendarProviderInfoFromJSONTyped,
    CalendarProviderInfoToJSON,
    CalendarProviderInfoToJSONTyped,
} from './CalendarProviderInfo';

/**
 * Registered calendar providers. Returned regardless of whether
 * the caller has connected any.
 * 
 * @export
 * @interface CalendarProvidersInfo
 */
export interface CalendarProvidersInfo {
    /**
     * 
     * @type {Array<CalendarProviderInfo>}
     * @memberof CalendarProvidersInfo
     */
    providers: Array<CalendarProviderInfo>;
}

/**
 * Check if a given object implements the CalendarProvidersInfo interface.
 */
export function instanceOfCalendarProvidersInfo(value: object): value is CalendarProvidersInfo {
    if (!('providers' in value) || value['providers'] === undefined) return false;
    return true;
}

export function CalendarProvidersInfoFromJSON(json: any): CalendarProvidersInfo {
    return CalendarProvidersInfoFromJSONTyped(json, false);
}

export function CalendarProvidersInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarProvidersInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'providers': ((json['providers'] as Array<any>).map(CalendarProviderInfoFromJSON)),
    };
}

export function CalendarProvidersInfoToJSON(json: any): CalendarProvidersInfo {
    return CalendarProvidersInfoToJSONTyped(json, false);
}

export function CalendarProvidersInfoToJSONTyped(value?: CalendarProvidersInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providers': ((value['providers'] as Array<any>).map(CalendarProviderInfoToJSON)),
    };
}

