/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentListResponse
 */
export interface CommentListResponse {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof CommentListResponse
     */
    comments: Array<Comment>;
    /**
     * 
     * @type {number}
     * @memberof CommentListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the CommentListResponse interface.
 */
export function instanceOfCommentListResponse(value: object): value is CommentListResponse {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CommentListResponseFromJSON(json: any): CommentListResponse {
    return CommentListResponseFromJSONTyped(json, false);
}

export function CommentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(CommentFromJSON)),
        'total': json['total'],
    };
}

export function CommentListResponseToJSON(json: any): CommentListResponse {
    return CommentListResponseToJSONTyped(json, false);
}

export function CommentListResponseToJSONTyped(value?: CommentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': ((value['comments'] as Array<any>).map(CommentToJSON)),
        'total': value['total'],
    };
}

