/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Video/phone conference details. `type` is canonical (`spatio`,
 * `meet`, `zoom`, `teams`); other provider-specific values are
 * accepted as opaque strings. The Spatio invite email pipeline
 * only fires for native events or events with `type: spatio`.
 * 
 * @export
 * @interface ConferenceData
 */
export interface ConferenceData {
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    meeting_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    passcode?: string;
    /**
     * 
     * @type {string}
     * @memberof ConferenceData
     */
    access_code?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConferenceData
     */
    dial_in?: Array<string>;
}

/**
 * Check if a given object implements the ConferenceData interface.
 */
export function instanceOfConferenceData(value: object): value is ConferenceData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function ConferenceDataFromJSON(json: any): ConferenceData {
    return ConferenceDataFromJSONTyped(json, false);
}

export function ConferenceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConferenceData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'uri': json['uri'],
        'meeting_id': json['meeting_id'] == null ? undefined : json['meeting_id'],
        'passcode': json['passcode'] == null ? undefined : json['passcode'],
        'access_code': json['access_code'] == null ? undefined : json['access_code'],
        'dial_in': json['dial_in'] == null ? undefined : json['dial_in'],
    };
}

export function ConferenceDataToJSON(json: any): ConferenceData {
    return ConferenceDataToJSONTyped(json, false);
}

export function ConferenceDataToJSONTyped(value?: ConferenceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'uri': value['uri'],
        'meeting_id': value['meeting_id'],
        'passcode': value['passcode'],
        'access_code': value['access_code'],
        'dial_in': value['dial_in'],
    };
}

