/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationMessage
 */
export interface ConversationMessage {
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    conversation_id: string;
    /**
     * `user`, `assistant`, `system`, or `tool`.
     * @type {string}
     * @memberof ConversationMessage
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    content?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConversationMessage
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof ConversationMessage
     */
    created_at?: Date;
}

/**
 * Check if a given object implements the ConversationMessage interface.
 */
export function instanceOfConversationMessage(value: object): value is ConversationMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversation_id' in value) || value['conversation_id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ConversationMessageFromJSON(json: any): ConversationMessage {
    return ConversationMessageFromJSONTyped(json, false);
}

export function ConversationMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversation_id': json['conversation_id'],
        'role': json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function ConversationMessageToJSON(json: any): ConversationMessage {
    return ConversationMessageToJSONTyped(json, false);
}

export function ConversationMessageToJSONTyped(value?: ConversationMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversation_id': value['conversation_id'],
        'role': value['role'],
        'content': value['content'],
        'metadata': value['metadata'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    };
}

