/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationInvitationRequest
 */
export interface CreateOrganizationInvitationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationInvitationRequest
     */
    email: string;
    /**
     * 
     * @type {CreateOrganizationInvitationRequestRoleEnum}
     * @memberof CreateOrganizationInvitationRequest
     */
    role: CreateOrganizationInvitationRequestRoleEnum;
    /**
     * Optional — the invitee will also be added to this workspace
     * on accept. Defaults to the org's default workspace.
     * 
     * @type {string}
     * @memberof CreateOrganizationInvitationRequest
     */
    workspaceId?: string;
}


/**
 * @export
 */
export const CreateOrganizationInvitationRequestRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    BillingAdmin: 'billing_admin',
    Member: 'member'
} as const;
export type CreateOrganizationInvitationRequestRoleEnum = typeof CreateOrganizationInvitationRequestRoleEnum[keyof typeof CreateOrganizationInvitationRequestRoleEnum];


/**
 * Check if a given object implements the CreateOrganizationInvitationRequest interface.
 */
export function instanceOfCreateOrganizationInvitationRequest(value: object): value is CreateOrganizationInvitationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateOrganizationInvitationRequestFromJSON(json: any): CreateOrganizationInvitationRequest {
    return CreateOrganizationInvitationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
    };
}

export function CreateOrganizationInvitationRequestToJSON(json: any): CreateOrganizationInvitationRequest {
    return CreateOrganizationInvitationRequestToJSONTyped(json, false);
}

export function CreateOrganizationInvitationRequestToJSONTyped(value?: CreateOrganizationInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
        'workspaceId': value['workspaceId'],
    };
}

