/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentInput } from './AttachmentInput';
import {
    AttachmentInputFromJSON,
    AttachmentInputFromJSONTyped,
    AttachmentInputToJSON,
    AttachmentInputToJSONTyped,
} from './AttachmentInput';

/**
 * 
 * @export
 * @interface CreateDraftRequest
 */
export interface CreateDraftRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    accountId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDraftRequest
     */
    to?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDraftRequest
     */
    cc?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDraftRequest
     */
    bcc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDraftRequest
     */
    html?: boolean;
    /**
     * 
     * @type {Array<AttachmentInput>}
     * @memberof CreateDraftRequest
     */
    attachments?: Array<AttachmentInput>;
    /**
     * Provider thread id — set when this draft is a reply, so the
     * sent message lands inside the parent thread.
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    inReplyTo?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDraftRequest
     */
    references?: Array<string>;
}

/**
 * Check if a given object implements the CreateDraftRequest interface.
 */
export function instanceOfCreateDraftRequest(value: object): value is CreateDraftRequest {
    return true;
}

export function CreateDraftRequestFromJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestFromJSONTyped(json, false);
}

export function CreateDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'to': json['to'] == null ? undefined : json['to'],
        'cc': json['cc'] == null ? undefined : json['cc'],
        'bcc': json['bcc'] == null ? undefined : json['bcc'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
        'html': json['html'] == null ? undefined : json['html'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AttachmentInputFromJSON)),
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
        'inReplyTo': json['inReplyTo'] == null ? undefined : json['inReplyTo'],
        'references': json['references'] == null ? undefined : json['references'],
    };
}

export function CreateDraftRequestToJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestToJSONTyped(json, false);
}

export function CreateDraftRequestToJSONTyped(value?: CreateDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'to': value['to'],
        'cc': value['cc'],
        'bcc': value['bcc'],
        'subject': value['subject'],
        'body': value['body'],
        'html': value['html'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AttachmentInputToJSON)),
        'threadId': value['threadId'],
        'inReplyTo': value['inReplyTo'],
        'references': value['references'],
    };
}

