/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateTaskRequest
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {CreateTaskRequestPriorityEnum}
     * @memberof CreateTaskRequest
     */
    priority?: CreateTaskRequestPriorityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTaskRequest
     */
    labels?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTaskRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    assigneeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    parentTaskId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    sourcePlatform?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    sourceId?: string;
    /**
     * Optional override for the target connected account. May also
     * be passed as `?accountId=`.
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    provider?: string;
}


/**
 * @export
 */
export const CreateTaskRequestPriorityEnum = {
    None: 'none',
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;
export type CreateTaskRequestPriorityEnum = typeof CreateTaskRequestPriorityEnum[keyof typeof CreateTaskRequestPriorityEnum];


/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(value: object): value is CreateTaskRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'assigneeId': json['assigneeId'] == null ? undefined : json['assigneeId'],
        'parentTaskId': json['parentTaskId'] == null ? undefined : json['parentTaskId'],
        'type': json['type'] == null ? undefined : json['type'],
        'sourcePlatform': json['sourcePlatform'] == null ? undefined : json['sourcePlatform'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function CreateTaskRequestToJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestToJSONTyped(json, false);
}

export function CreateTaskRequestToJSONTyped(value?: CreateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString(),
        'priority': value['priority'],
        'labels': value['labels'],
        'tags': value['tags'],
        'assigneeId': value['assigneeId'],
        'parentTaskId': value['parentTaskId'],
        'type': value['type'],
        'sourcePlatform': value['sourcePlatform'],
        'sourceId': value['sourceId'],
        'accountId': value['accountId'],
        'provider': value['provider'],
    };
}

