/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DMReactionRequest
 */
export interface DMReactionRequest {
    /**
     * 
     * @type {string}
     * @memberof DMReactionRequest
     */
    emoji: string;
    /**
     * 
     * @type {string}
     * @memberof DMReactionRequest
     */
    accountId?: string;
}

/**
 * Check if a given object implements the DMReactionRequest interface.
 */
export function instanceOfDMReactionRequest(value: object): value is DMReactionRequest {
    if (!('emoji' in value) || value['emoji'] === undefined) return false;
    return true;
}

export function DMReactionRequestFromJSON(json: any): DMReactionRequest {
    return DMReactionRequestFromJSONTyped(json, false);
}

export function DMReactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DMReactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'emoji': json['emoji'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function DMReactionRequestToJSON(json: any): DMReactionRequest {
    return DMReactionRequestToJSONTyped(json, false);
}

export function DMReactionRequestToJSONTyped(value?: DMReactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emoji': value['emoji'],
        'accountId': value['accountId'],
    };
}

