/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * `reactions` shape is provider-specific; treat as opaque.
 * @export
 * @interface DMReactionResponse
 */
export interface DMReactionResponse {
    /**
     * Updated reaction list for the message.
     * @type {any}
     * @memberof DMReactionResponse
     */
    reactions?: any | null;
}

/**
 * Check if a given object implements the DMReactionResponse interface.
 */
export function instanceOfDMReactionResponse(value: object): value is DMReactionResponse {
    return true;
}

export function DMReactionResponseFromJSON(json: any): DMReactionResponse {
    return DMReactionResponseFromJSONTyped(json, false);
}

export function DMReactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DMReactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reactions': json['reactions'] == null ? undefined : json['reactions'],
    };
}

export function DMReactionResponseToJSON(json: any): DMReactionResponse {
    return DMReactionResponseToJSONTyped(json, false);
}

export function DMReactionResponseToJSONTyped(value?: DMReactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reactions': value['reactions'],
    };
}

