/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailFolder
 */
export interface EmailFolder {
    /**
     * 
     * @type {string}
     * @memberof EmailFolder
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmailFolder
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailFolder
     */
    accountId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EmailFolder
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof EmailFolder
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the EmailFolder interface.
 */
export function instanceOfEmailFolder(value: object): value is EmailFolder {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function EmailFolderFromJSON(json: any): EmailFolder {
    return EmailFolderFromJSONTyped(json, false);
}

export function EmailFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailFolder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function EmailFolderToJSON(json: any): EmailFolder {
    return EmailFolderToJSONTyped(json, false);
}

export function EmailFolderToJSONTyped(value?: EmailFolder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'accountId': value['accountId'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

