/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportPDFRequestRasterizedSlidesInner
 */
export interface ExportPDFRequestRasterizedSlidesInner {
    /**
     * 
     * @type {string}
     * @memberof ExportPDFRequestRasterizedSlidesInner
     */
    slideId: string;
    /**
     * Base64-encoded PNG.
     * @type {string}
     * @memberof ExportPDFRequestRasterizedSlidesInner
     */
    png: string;
}

/**
 * Check if a given object implements the ExportPDFRequestRasterizedSlidesInner interface.
 */
export function instanceOfExportPDFRequestRasterizedSlidesInner(value: object): value is ExportPDFRequestRasterizedSlidesInner {
    if (!('slideId' in value) || value['slideId'] === undefined) return false;
    if (!('png' in value) || value['png'] === undefined) return false;
    return true;
}

export function ExportPDFRequestRasterizedSlidesInnerFromJSON(json: any): ExportPDFRequestRasterizedSlidesInner {
    return ExportPDFRequestRasterizedSlidesInnerFromJSONTyped(json, false);
}

export function ExportPDFRequestRasterizedSlidesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportPDFRequestRasterizedSlidesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'slideId': json['slideId'],
        'png': json['png'],
    };
}

export function ExportPDFRequestRasterizedSlidesInnerToJSON(json: any): ExportPDFRequestRasterizedSlidesInner {
    return ExportPDFRequestRasterizedSlidesInnerToJSONTyped(json, false);
}

export function ExportPDFRequestRasterizedSlidesInnerToJSONTyped(value?: ExportPDFRequestRasterizedSlidesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slideId': value['slideId'],
        'png': value['png'],
    };
}

