/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A unified-feed item. Source-aware — `category` indicates which
 * upstream platform (mail, dm, channel, mention, system) produced
 * it; `id` is the inbox-item id (not the underlying message id).
 * 
 * @export
 * @interface InboxItem
 */
export interface InboxItem {
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    snippet?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    accountId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InboxItem
     */
    isRead?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InboxItem
     */
    isMention?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InboxItem
     */
    timestamp?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InboxItem
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the InboxItem interface.
 */
export function instanceOfInboxItem(value: object): value is InboxItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function InboxItemFromJSON(json: any): InboxItem {
    return InboxItemFromJSONTyped(json, false);
}

export function InboxItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'title': json['title'] == null ? undefined : json['title'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
        'isMention': json['isMention'] == null ? undefined : json['isMention'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function InboxItemToJSON(json: any): InboxItem {
    return InboxItemToJSONTyped(json, false);
}

export function InboxItemToJSONTyped(value?: InboxItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'title': value['title'],
        'snippet': value['snippet'],
        'source': value['source'],
        'sourceId': value['sourceId'],
        'accountId': value['accountId'],
        'isRead': value['isRead'],
        'isMention': value['isMention'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'metadata': value['metadata'],
    };
}

