/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarAccountError } from './CalendarAccountError';
import {
    CalendarAccountErrorFromJSON,
    CalendarAccountErrorFromJSONTyped,
    CalendarAccountErrorToJSON,
    CalendarAccountErrorToJSONTyped,
} from './CalendarAccountError';
import type { ListEventsData } from './ListEventsData';
import {
    ListEventsDataFromJSON,
    ListEventsDataFromJSONTyped,
    ListEventsDataToJSON,
    ListEventsDataToJSONTyped,
} from './ListEventsData';

/**
 * 
 * @export
 * @interface ListCalendarEvents200Response
 */
export interface ListCalendarEvents200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListCalendarEvents200Response
     */
    success: boolean;
    /**
     * 
     * @type {ListEventsData}
     * @memberof ListCalendarEvents200Response
     */
    data?: ListEventsData;
    /**
     * 
     * @type {Array<CalendarAccountError>}
     * @memberof ListCalendarEvents200Response
     */
    errors?: Array<CalendarAccountError>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ListCalendarEvents200Response
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ListCalendarEvents200Response interface.
 */
export function instanceOfListCalendarEvents200Response(value: object): value is ListCalendarEvents200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ListCalendarEvents200ResponseFromJSON(json: any): ListCalendarEvents200Response {
    return ListCalendarEvents200ResponseFromJSONTyped(json, false);
}

export function ListCalendarEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCalendarEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ListEventsDataFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(CalendarAccountErrorFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ListCalendarEvents200ResponseToJSON(json: any): ListCalendarEvents200Response {
    return ListCalendarEvents200ResponseToJSONTyped(json, false);
}

export function ListCalendarEvents200ResponseToJSONTyped(value?: ListCalendarEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListEventsDataToJSON(value['data']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(CalendarAccountErrorToJSON)),
        'metadata': value['metadata'],
    };
}

