/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';

/**
 * 
 * @export
 * @interface ListLabelsResponse
 */
export interface ListLabelsResponse {
    /**
     * 
     * @type {Array<Label>}
     * @memberof ListLabelsResponse
     */
    labels: Array<Label>;
    /**
     * 
     * @type {string}
     * @memberof ListLabelsResponse
     */
    provider: string;
}

/**
 * Check if a given object implements the ListLabelsResponse interface.
 */
export function instanceOfListLabelsResponse(value: object): value is ListLabelsResponse {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function ListLabelsResponseFromJSON(json: any): ListLabelsResponse {
    return ListLabelsResponseFromJSONTyped(json, false);
}

export function ListLabelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLabelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': ((json['labels'] as Array<any>).map(LabelFromJSON)),
        'provider': json['provider'],
    };
}

export function ListLabelsResponseToJSON(json: any): ListLabelsResponse {
    return ListLabelsResponseToJSONTyped(json, false);
}

export function ListLabelsResponseToJSONTyped(value?: ListLabelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': ((value['labels'] as Array<any>).map(LabelToJSON)),
        'provider': value['provider'],
    };
}

