/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelRecord
 */
export interface ModelRecord {
    /**
     * 
     * @type {string}
     * @memberof ModelRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRecord
     */
    organization_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRecord
     */
    record_type_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRecord
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ModelRecord
     */
    attributes?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ModelRecord
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof ModelRecord
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModelRecord
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the ModelRecord interface.
 */
export function instanceOfModelRecord(value: object): value is ModelRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ModelRecordFromJSON(json: any): ModelRecord {
    return ModelRecordFromJSONTyped(json, false);
}

export function ModelRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'] == null ? undefined : json['organization_id'],
        'record_type_id': json['record_type_id'] == null ? undefined : json['record_type_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ModelRecordToJSON(json: any): ModelRecord {
    return ModelRecordToJSONTyped(json, false);
}

export function ModelRecordToJSONTyped(value?: ModelRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'record_type_id': value['record_type_id'],
        'name': value['name'],
        'attributes': value['attributes'],
        'metadata': value['metadata'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

