/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationWorkspacesInner } from './OrganizationWorkspacesInner';
import {
    OrganizationWorkspacesInnerFromJSON,
    OrganizationWorkspacesInnerFromJSONTyped,
    OrganizationWorkspacesInnerToJSON,
    OrganizationWorkspacesInnerToJSONTyped,
} from './OrganizationWorkspacesInner';

/**
 * Organization summary used in list responses (`GET /v1/organizations`,
 * `GET /v1/organizations/{id}/workspaces`). Returned with camelCase
 * field names.
 * 
 * NB: The single-org GET `/v1/organizations/{id}` returns a
 * *different shape* (`OrganizationDetailLegacy`, PascalCase keys)
 * today — see that schema for the wire-level reality. This is a
 * known inconsistency the platform-service is expected to
 * converge on the camelCase shape in a future cleanup.
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    logoUrl?: string | null;
    /**
     * The caller's role in this org (`owner`, `admin`, `billing_admin`, `member`).
     * @type {string}
     * @memberof Organization
     */
    role: string;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    workspaceCount?: number;
    /**
     * Compact workspace summaries embedded in the org-list response.
     * @type {Array<OrganizationWorkspacesInner>}
     * @memberof Organization
     */
    workspaces?: Array<OrganizationWorkspacesInner>;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'role': json['role'],
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'workspaceCount': json['workspaceCount'] == null ? undefined : json['workspaceCount'],
        'workspaces': json['workspaces'] == null ? undefined : ((json['workspaces'] as Array<any>).map(OrganizationWorkspacesInnerFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Organization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
        'role': value['role'],
        'memberCount': value['memberCount'],
        'workspaceCount': value['workspaceCount'],
        'workspaces': value['workspaces'] == null ? undefined : ((value['workspaces'] as Array<any>).map(OrganizationWorkspacesInnerToJSON)),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

