/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationMemberInvitedBy } from './OrganizationMemberInvitedBy';
import {
    OrganizationMemberInvitedByFromJSON,
    OrganizationMemberInvitedByFromJSONTyped,
    OrganizationMemberInvitedByToJSON,
    OrganizationMemberInvitedByToJSONTyped,
} from './OrganizationMemberInvitedBy';

/**
 * 
 * @export
 * @interface OrganizationInvitation
 */
export interface OrganizationInvitation {
    /**
     * 
     * @type {string}
     * @memberof OrganizationInvitation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationInvitation
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationInvitation
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationInvitation
     */
    role: string;
    /**
     * Opaque invitation token (omitted on list responses).
     * @type {string}
     * @memberof OrganizationInvitation
     */
    token?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    acceptedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationInvitation
     */
    revokedAt?: Date | null;
    /**
     * 
     * @type {OrganizationMemberInvitedBy}
     * @memberof OrganizationInvitation
     */
    invitedBy?: OrganizationMemberInvitedBy;
    /**
     * 
     * @type {OrganizationInvitationStatusEnum}
     * @memberof OrganizationInvitation
     */
    status?: OrganizationInvitationStatusEnum;
}


/**
 * @export
 */
export const OrganizationInvitationStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Revoked: 'revoked',
    Expired: 'expired'
} as const;
export type OrganizationInvitationStatusEnum = typeof OrganizationInvitationStatusEnum[keyof typeof OrganizationInvitationStatusEnum];


/**
 * Check if a given object implements the OrganizationInvitation interface.
 */
export function instanceOfOrganizationInvitation(value: object): value is OrganizationInvitation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrganizationInvitationFromJSON(json: any): OrganizationInvitation {
    return OrganizationInvitationFromJSONTyped(json, false);
}

export function OrganizationInvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationInvitation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'email': json['email'],
        'role': json['role'],
        'token': json['token'] == null ? undefined : json['token'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'acceptedAt': json['acceptedAt'] == null ? undefined : (new Date(json['acceptedAt'])),
        'revokedAt': json['revokedAt'] == null ? undefined : (new Date(json['revokedAt'])),
        'invitedBy': json['invitedBy'] == null ? undefined : OrganizationMemberInvitedByFromJSON(json['invitedBy']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function OrganizationInvitationToJSON(json: any): OrganizationInvitation {
    return OrganizationInvitationToJSONTyped(json, false);
}

export function OrganizationInvitationToJSONTyped(value?: OrganizationInvitation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'email': value['email'],
        'role': value['role'],
        'token': value['token'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : value['acceptedAt'].toISOString(),
        'revokedAt': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
        'invitedBy': OrganizationMemberInvitedByToJSON(value['invitedBy']),
        'status': value['status'],
    };
}

