/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Curated featured agents — read-only, surfaced by the renderer's
 * "preconfigured" picker. Not full Agent records; minimal display
 * metadata only.
 * 
 * @export
 * @interface PreconfiguredAgent
 */
export interface PreconfiguredAgent {
    /**
     * 
     * @type {string}
     * @memberof PreconfiguredAgent
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof PreconfiguredAgent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PreconfiguredAgent
     */
    tagline?: string;
    /**
     * 
     * @type {string}
     * @memberof PreconfiguredAgent
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PreconfiguredAgent
     */
    icon?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PreconfiguredAgent
     */
    hasAllTools?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PreconfiguredAgent
     */
    toolCount?: number;
}

/**
 * Check if a given object implements the PreconfiguredAgent interface.
 */
export function instanceOfPreconfiguredAgent(value: object): value is PreconfiguredAgent {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PreconfiguredAgentFromJSON(json: any): PreconfiguredAgent {
    return PreconfiguredAgentFromJSONTyped(json, false);
}

export function PreconfiguredAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreconfiguredAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agentId'],
        'name': json['name'],
        'tagline': json['tagline'] == null ? undefined : json['tagline'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'hasAllTools': json['hasAllTools'] == null ? undefined : json['hasAllTools'],
        'toolCount': json['toolCount'] == null ? undefined : json['toolCount'],
    };
}

export function PreconfiguredAgentToJSON(json: any): PreconfiguredAgent {
    return PreconfiguredAgentToJSONTyped(json, false);
}

export function PreconfiguredAgentToJSONTyped(value?: PreconfiguredAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentId': value['agentId'],
        'name': value['name'],
        'tagline': value['tagline'],
        'description': value['description'],
        'icon': value['icon'],
        'hasAllTools': value['hasAllTools'],
        'toolCount': value['toolCount'],
    };
}

