/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A slide deck. Presentations belong to one connected account
 * (`accountId` + `provider`). Native deck storage lives in Spatio's
 * DB; external providers (Google Slides, etc.) round-trip.
 * 
 * @export
 * @interface Presentation
 */
export interface Presentation {
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    ownerUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    description?: string;
    /**
     * Free-form theme id; provider-specific.
     * @type {string}
     * @memberof Presentation
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof Presentation
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof Presentation
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Presentation
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Presentation
     */
    lastViewedAt?: Date | null;
}

/**
 * Check if a given object implements the Presentation interface.
 */
export function instanceOfPresentation(value: object): value is Presentation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PresentationFromJSON(json: any): Presentation {
    return PresentationFromJSONTyped(json, false);
}

export function PresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Presentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'ownerUserId': json['ownerUserId'] == null ? undefined : json['ownerUserId'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'lastViewedAt': json['lastViewedAt'] == null ? undefined : (new Date(json['lastViewedAt'])),
    };
}

export function PresentationToJSON(json: any): Presentation {
    return PresentationToJSONTyped(json, false);
}

export function PresentationToJSONTyped(value?: Presentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'accountId': value['accountId'],
        'ownerUserId': value['ownerUserId'],
        'title': value['title'],
        'description': value['description'],
        'theme': value['theme'],
        'thumbnailUrl': value['thumbnailUrl'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'lastViewedAt': value['lastViewedAt'] == null ? value['lastViewedAt'] : value['lastViewedAt'].toISOString(),
    };
}

