/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returned by `GET /invitations/{token}` (unauthenticated).
 * Lets the renderer show invitation details (workspace name,
 * inviter, role) before the user signs in.
 * 
 * @export
 * @interface PublicInvitationPayload
 */
export interface PublicInvitationPayload {
    /**
     * 
     * @type {PublicInvitationPayloadKindEnum}
     * @memberof PublicInvitationPayload
     */
    kind: PublicInvitationPayloadKindEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicInvitationPayload
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvitationPayload
     */
    workspaceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvitationPayload
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvitationPayload
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PublicInvitationPayload
     */
    role: string;
    /**
     * 
     * @type {PublicInvitationPayloadStatusEnum}
     * @memberof PublicInvitationPayload
     */
    status: PublicInvitationPayloadStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PublicInvitationPayload
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PublicInvitationPayload
     */
    createdAt?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PublicInvitationPayload
     */
    workspace?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PublicInvitationPayload
     */
    organization?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PublicInvitationPayload
     */
    invitedBy?: { [key: string]: any; };
}


/**
 * @export
 */
export const PublicInvitationPayloadKindEnum = {
    Workspace: 'workspace',
    Organization: 'organization'
} as const;
export type PublicInvitationPayloadKindEnum = typeof PublicInvitationPayloadKindEnum[keyof typeof PublicInvitationPayloadKindEnum];

/**
 * @export
 */
export const PublicInvitationPayloadStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Revoked: 'revoked',
    Expired: 'expired'
} as const;
export type PublicInvitationPayloadStatusEnum = typeof PublicInvitationPayloadStatusEnum[keyof typeof PublicInvitationPayloadStatusEnum];


/**
 * Check if a given object implements the PublicInvitationPayload interface.
 */
export function instanceOfPublicInvitationPayload(value: object): value is PublicInvitationPayload {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PublicInvitationPayloadFromJSON(json: any): PublicInvitationPayload {
    return PublicInvitationPayloadFromJSONTyped(json, false);
}

export function PublicInvitationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInvitationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'id': json['id'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'email': json['email'],
        'role': json['role'],
        'status': json['status'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'invitedBy': json['invitedBy'] == null ? undefined : json['invitedBy'],
    };
}

export function PublicInvitationPayloadToJSON(json: any): PublicInvitationPayload {
    return PublicInvitationPayloadToJSONTyped(json, false);
}

export function PublicInvitationPayloadToJSONTyped(value?: PublicInvitationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'organizationId': value['organizationId'],
        'email': value['email'],
        'role': value['role'],
        'status': value['status'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'workspace': value['workspace'],
        'organization': value['organization'],
        'invitedBy': value['invitedBy'],
    };
}

