/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Agent-authored proposal that surfaces on the home feed. Status
 * transitions: `pending` → `accepted | dismissed | expired`.
 * 
 * @export
 * @interface Recommendation
 */
export interface Recommendation {
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    workspaceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    userId?: string;
    /**
     * Provider-tagged proposal kind (e.g. `note.draft`, `task.followup`).
     * @type {string}
     * @memberof Recommendation
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    body?: string;
    /**
     * 
     * @type {RecommendationStatusEnum}
     * @memberof Recommendation
     */
    status: RecommendationStatusEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Recommendation
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof Recommendation
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Recommendation
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Recommendation
     */
    expiresAt?: Date | null;
}


/**
 * @export
 */
export const RecommendationStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Dismissed: 'dismissed',
    Expired: 'expired'
} as const;
export type RecommendationStatusEnum = typeof RecommendationStatusEnum[keyof typeof RecommendationStatusEnum];


/**
 * Check if a given object implements the Recommendation interface.
 */
export function instanceOfRecommendation(value: object): value is Recommendation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RecommendationFromJSON(json: any): Recommendation {
    return RecommendationFromJSONTyped(json, false);
}

export function RecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'status': json['status'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function RecommendationToJSON(json: any): Recommendation {
    return RecommendationToJSONTyped(json, false);
}

export function RecommendationToJSONTyped(value?: Recommendation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'userId': value['userId'],
        'kind': value['kind'],
        'title': value['title'],
        'body': value['body'],
        'status': value['status'],
        'payload': value['payload'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

