/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReminderMethod = {
    Email: 'email',
    Popup: 'popup',
    Sms: 'sms',
    Push: 'push'
} as const;
export type ReminderMethod = typeof ReminderMethod[keyof typeof ReminderMethod];


export function instanceOfReminderMethod(value: any): boolean {
    for (const key in ReminderMethod) {
        if (Object.prototype.hasOwnProperty.call(ReminderMethod, key)) {
            if (ReminderMethod[key as keyof typeof ReminderMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReminderMethodFromJSON(json: any): ReminderMethod {
    return ReminderMethodFromJSONTyped(json, false);
}

export function ReminderMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderMethod {
    return json as ReminderMethod;
}

export function ReminderMethodToJSON(value?: ReminderMethod | null): any {
    return value as any;
}

export function ReminderMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): ReminderMethod {
    return value as ReminderMethod;
}

