/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReminderMethod } from './ReminderMethod';
import {
    ReminderMethodFromJSON,
    ReminderMethodFromJSONTyped,
    ReminderMethodToJSON,
    ReminderMethodToJSONTyped,
} from './ReminderMethod';

/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {ReminderMethod}
     * @memberof Reminder
     */
    method: ReminderMethod;
    /**
     * Trigger time in minutes before the event start.
     * @type {number}
     * @memberof Reminder
     */
    minutes: number;
}



/**
 * Check if a given object implements the Reminder interface.
 */
export function instanceOfReminder(value: object): value is Reminder {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('minutes' in value) || value['minutes'] === undefined) return false;
    return true;
}

export function ReminderFromJSON(json: any): Reminder {
    return ReminderFromJSONTyped(json, false);
}

export function ReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reminder {
    if (json == null) {
        return json;
    }
    return {
        
        'method': ReminderMethodFromJSON(json['method']),
        'minutes': json['minutes'],
    };
}

export function ReminderToJSON(json: any): Reminder {
    return ReminderToJSONTyped(json, false);
}

export function ReminderToJSONTyped(value?: Reminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': ReminderMethodToJSON(value['method']),
        'minutes': value['minutes'],
    };
}

