/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoutineRunCompleteRequest
 */
export interface RoutineRunCompleteRequest {
    /**
     * 
     * @type {string}
     * @memberof RoutineRunCompleteRequest
     */
    status?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RoutineRunCompleteRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RoutineRunCompleteRequest interface.
 */
export function instanceOfRoutineRunCompleteRequest(value: object): value is RoutineRunCompleteRequest {
    return true;
}

export function RoutineRunCompleteRequestFromJSON(json: any): RoutineRunCompleteRequest {
    return RoutineRunCompleteRequestFromJSONTyped(json, false);
}

export function RoutineRunCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutineRunCompleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function RoutineRunCompleteRequestToJSON(json: any): RoutineRunCompleteRequest {
    return RoutineRunCompleteRequestToJSONTyped(json, false);
}

export function RoutineRunCompleteRequestToJSONTyped(value?: RoutineRunCompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'metadata': value['metadata'],
    };
}

