/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoutineRun
 */
export interface RoutineRun {
    /**
     * 
     * @type {string}
     * @memberof RoutineRun
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoutineRun
     */
    routineId?: string;
    /**
     * 
     * @type {string}
     * @memberof RoutineRun
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof RoutineRun
     */
    progress?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RoutineRun
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof RoutineRun
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoutineRun
     */
    completedAt?: Date | null;
}

/**
 * Check if a given object implements the RoutineRun interface.
 */
export function instanceOfRoutineRun(value: object): value is RoutineRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RoutineRunFromJSON(json: any): RoutineRun {
    return RoutineRunFromJSONTyped(json, false);
}

export function RoutineRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutineRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'routineId': json['routineId'] == null ? undefined : json['routineId'],
        'status': json['status'] == null ? undefined : json['status'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
    };
}

export function RoutineRunToJSON(json: any): RoutineRun {
    return RoutineRunToJSONTyped(json, false);
}

export function RoutineRunToJSONTyped(value?: RoutineRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'routineId': value['routineId'],
        'status': value['status'],
        'progress': value['progress'],
        'metadata': value['metadata'],
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
    };
}

