/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMessageRequest
 */
export interface SaveMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveMessageRequest
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMessageRequest
     */
    content: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SaveMessageRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SaveMessageRequest interface.
 */
export function instanceOfSaveMessageRequest(value: object): value is SaveMessageRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SaveMessageRequestFromJSON(json: any): SaveMessageRequest {
    return SaveMessageRequestFromJSONTyped(json, false);
}

export function SaveMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function SaveMessageRequestToJSON(json: any): SaveMessageRequest {
    return SaveMessageRequestToJSONTyped(json, false);
}

export function SaveMessageRequestToJSONTyped(value?: SaveMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'metadata': value['metadata'],
    };
}

