/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendChatMessageResponse
 */
export interface SendChatMessageResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SendChatMessageResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageResponse
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageResponse
     */
    channelId?: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageResponse
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageResponse
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the SendChatMessageResponse interface.
 */
export function instanceOfSendChatMessageResponse(value: object): value is SendChatMessageResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function SendChatMessageResponseFromJSON(json: any): SendChatMessageResponse {
    return SendChatMessageResponseFromJSONTyped(json, false);
}

export function SendChatMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendChatMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'messageId': json['messageId'],
        'channelId': json['channelId'] == null ? undefined : json['channelId'],
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
        'provider': json['provider'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SendChatMessageResponseToJSON(json: any): SendChatMessageResponse {
    return SendChatMessageResponseToJSONTyped(json, false);
}

export function SendChatMessageResponseToJSONTyped(value?: SendChatMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'messageId': value['messageId'],
        'channelId': value['channelId'],
        'threadId': value['threadId'],
        'provider': value['provider'],
        'error': value['error'],
    };
}

