/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public share configuration for a note. Owner-only mutation;
 * unauthenticated readers consume `GET /public/notes/{token}` instead.
 * 
 * @export
 * @interface ShareSettings
 */
export interface ShareSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ShareSettings
     */
    isPublic: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShareSettings
     */
    hasPassword: boolean;
    /**
     * Opaque token embedded in the public URL. Empty when
     * `isPublic` is false.
     * 
     * @type {string}
     * @memberof ShareSettings
     */
    shareToken?: string;
    /**
     * Fully-qualified public viewer URL. Computed server-side from
     * `PUBLIC_VIEWER_BASE` (defaults to `https://spatio.app`) and the
     * share token. Empty when the note is private.
     * 
     * @type {string}
     * @memberof ShareSettings
     */
    shareUrl?: string;
    /**
     * When the current password was set, if any.
     * @type {Date}
     * @memberof ShareSettings
     */
    passwordSetAt?: Date;
}

/**
 * Check if a given object implements the ShareSettings interface.
 */
export function instanceOfShareSettings(value: object): value is ShareSettings {
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('hasPassword' in value) || value['hasPassword'] === undefined) return false;
    return true;
}

export function ShareSettingsFromJSON(json: any): ShareSettings {
    return ShareSettingsFromJSONTyped(json, false);
}

export function ShareSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'isPublic': json['isPublic'],
        'hasPassword': json['hasPassword'],
        'shareToken': json['shareToken'] == null ? undefined : json['shareToken'],
        'shareUrl': json['shareUrl'] == null ? undefined : json['shareUrl'],
        'passwordSetAt': json['passwordSetAt'] == null ? undefined : (new Date(json['passwordSetAt'])),
    };
}

export function ShareSettingsToJSON(json: any): ShareSettings {
    return ShareSettingsToJSONTyped(json, false);
}

export function ShareSettingsToJSONTyped(value?: ShareSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPublic': value['isPublic'],
        'hasPassword': value['hasPassword'],
        'shareToken': value['shareToken'],
        'shareUrl': value['shareUrl'],
        'passwordSetAt': value['passwordSetAt'] == null ? value['passwordSetAt'] : value['passwordSetAt'].toISOString(),
    };
}

