/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatus } from './AccountStatus';
import {
    AccountStatusFromJSON,
    AccountStatusFromJSONTyped,
    AccountStatusToJSON,
    AccountStatusToJSONTyped,
} from './AccountStatus';
import type { Sheet } from './Sheet';
import {
    SheetFromJSON,
    SheetFromJSONTyped,
    SheetToJSON,
    SheetToJSONTyped,
} from './Sheet';

/**
 * Fan-out response for `GET /v1/sheets`. `items` aggregates sheets
 * across every connected account; `accounts` carries one row per
 * contributing connection — including failures.
 * 
 * @export
 * @interface SheetListEnvelope
 */
export interface SheetListEnvelope {
    /**
     * 
     * @type {Array<Sheet>}
     * @memberof SheetListEnvelope
     */
    items: Array<Sheet>;
    /**
     * 
     * @type {Array<AccountStatus>}
     * @memberof SheetListEnvelope
     */
    accounts: Array<AccountStatus>;
}

/**
 * Check if a given object implements the SheetListEnvelope interface.
 */
export function instanceOfSheetListEnvelope(value: object): value is SheetListEnvelope {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function SheetListEnvelopeFromJSON(json: any): SheetListEnvelope {
    return SheetListEnvelopeFromJSONTyped(json, false);
}

export function SheetListEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetListEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SheetFromJSON)),
        'accounts': ((json['accounts'] as Array<any>).map(AccountStatusFromJSON)),
    };
}

export function SheetListEnvelopeToJSON(json: any): SheetListEnvelope {
    return SheetListEnvelopeToJSONTyped(json, false);
}

export function SheetListEnvelopeToJSONTyped(value?: SheetListEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SheetToJSON)),
        'accounts': ((value['accounts'] as Array<any>).map(AccountStatusToJSON)),
    };
}

