/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInMethodsProvidersInner
 */
export interface SignInMethodsProvidersInner {
    /**
     * OAuth IdP: `GOOGLE`, `GITHUB`, etc.
     * @type {string}
     * @memberof SignInMethodsProvidersInner
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof SignInMethodsProvidersInner
     */
    accountEmail?: string;
    /**
     * 
     * @type {Date}
     * @memberof SignInMethodsProvidersInner
     */
    linkedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SignInMethodsProvidersInner
     */
    lastUsedAt?: Date | null;
}

/**
 * Check if a given object implements the SignInMethodsProvidersInner interface.
 */
export function instanceOfSignInMethodsProvidersInner(value: object): value is SignInMethodsProvidersInner {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function SignInMethodsProvidersInnerFromJSON(json: any): SignInMethodsProvidersInner {
    return SignInMethodsProvidersInnerFromJSONTyped(json, false);
}

export function SignInMethodsProvidersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInMethodsProvidersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'accountEmail': json['accountEmail'] == null ? undefined : json['accountEmail'],
        'linkedAt': json['linkedAt'] == null ? undefined : (new Date(json['linkedAt'])),
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : (new Date(json['lastUsedAt'])),
    };
}

export function SignInMethodsProvidersInnerToJSON(json: any): SignInMethodsProvidersInner {
    return SignInMethodsProvidersInnerToJSONTyped(json, false);
}

export function SignInMethodsProvidersInnerToJSONTyped(value?: SignInMethodsProvidersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'accountEmail': value['accountEmail'],
        'linkedAt': value['linkedAt'] == null ? value['linkedAt'] : value['linkedAt'].toISOString(),
        'lastUsedAt': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
    };
}

