/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OAuth/native integration descriptor. Open shape — categories
 * add provider-specific capability flags. Treat unknown fields
 * as additive.
 * 
 * @export
 * @interface SpatioConnection
 */
export interface SpatioConnection {
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    authType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SpatioConnection
     */
    connected?: boolean;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SpatioConnection
     */
    connectedAccounts?: Array<{ [key: string]: any; }> | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SpatioConnection
     */
    capabilities?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    gradientFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    gradientTo?: string;
    /**
     * 
     * @type {string}
     * @memberof SpatioConnection
     */
    icon?: string;
}

/**
 * Check if a given object implements the SpatioConnection interface.
 */
export function instanceOfSpatioConnection(value: object): value is SpatioConnection {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SpatioConnectionFromJSON(json: any): SpatioConnection {
    return SpatioConnectionFromJSONTyped(json, false);
}

export function SpatioConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatioConnection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'category': json['category'] == null ? undefined : json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'authType': json['authType'] == null ? undefined : json['authType'],
        'connected': json['connected'] == null ? undefined : json['connected'],
        'connectedAccounts': json['connectedAccounts'] == null ? undefined : json['connectedAccounts'],
        'capabilities': json['capabilities'] == null ? undefined : json['capabilities'],
        'gradientFrom': json['gradientFrom'] == null ? undefined : json['gradientFrom'],
        'gradientTo': json['gradientTo'] == null ? undefined : json['gradientTo'],
        'icon': json['icon'] == null ? undefined : json['icon'],
    };
}

export function SpatioConnectionToJSON(json: any): SpatioConnection {
    return SpatioConnectionToJSONTyped(json, false);
}

export function SpatioConnectionToJSONTyped(value?: SpatioConnection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'category': value['category'],
        'description': value['description'],
        'authType': value['authType'],
        'connected': value['connected'],
        'connectedAccounts': value['connectedAccounts'],
        'capabilities': value['capabilities'],
        'gradientFrom': value['gradientFrom'],
        'gradientTo': value['gradientTo'],
        'icon': value['icon'],
    };
}

