/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskComment } from './TaskComment';
import {
    TaskCommentFromJSON,
    TaskCommentFromJSONTyped,
    TaskCommentToJSON,
    TaskCommentToJSONTyped,
} from './TaskComment';

/**
 * 
 * @export
 * @interface TaskCommentMutationResponse
 */
export interface TaskCommentMutationResponse {
    /**
     * 
     * @type {TaskComment}
     * @memberof TaskCommentMutationResponse
     */
    comment: TaskComment;
    /**
     * 
     * @type {boolean}
     * @memberof TaskCommentMutationResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the TaskCommentMutationResponse interface.
 */
export function instanceOfTaskCommentMutationResponse(value: object): value is TaskCommentMutationResponse {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function TaskCommentMutationResponseFromJSON(json: any): TaskCommentMutationResponse {
    return TaskCommentMutationResponseFromJSONTyped(json, false);
}

export function TaskCommentMutationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCommentMutationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': TaskCommentFromJSON(json['comment']),
        'success': json['success'],
    };
}

export function TaskCommentMutationResponseToJSON(json: any): TaskCommentMutationResponse {
    return TaskCommentMutationResponseToJSONTyped(json, false);
}

export function TaskCommentMutationResponseToJSONTyped(value?: TaskCommentMutationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': TaskCommentToJSON(value['comment']),
        'success': value['success'],
    };
}

