/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskProvidersInfoPlatform } from './TaskProvidersInfoPlatform';
import {
    TaskProvidersInfoPlatformFromJSON,
    TaskProvidersInfoPlatformFromJSONTyped,
    TaskProvidersInfoPlatformToJSON,
    TaskProvidersInfoPlatformToJSONTyped,
} from './TaskProvidersInfoPlatform';

/**
 * Metadata about which task providers are connected and what the
 * Tasks platform itself reports for its name + description.
 * 
 * @export
 * @interface TaskProvidersInfo
 */
export interface TaskProvidersInfo {
    /**
     * Registered provider ids (e.g. `native-tasks`, `linear`).
     * @type {Array<string>}
     * @memberof TaskProvidersInfo
     */
    providers: Array<string>;
    /**
     * 
     * @type {TaskProvidersInfoPlatform}
     * @memberof TaskProvidersInfo
     */
    platform: TaskProvidersInfoPlatform;
}

/**
 * Check if a given object implements the TaskProvidersInfo interface.
 */
export function instanceOfTaskProvidersInfo(value: object): value is TaskProvidersInfo {
    if (!('providers' in value) || value['providers'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function TaskProvidersInfoFromJSON(json: any): TaskProvidersInfo {
    return TaskProvidersInfoFromJSONTyped(json, false);
}

export function TaskProvidersInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProvidersInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'providers': json['providers'],
        'platform': TaskProvidersInfoPlatformFromJSON(json['platform']),
    };
}

export function TaskProvidersInfoToJSON(json: any): TaskProvidersInfo {
    return TaskProvidersInfoToJSONTyped(json, false);
}

export function TaskProvidersInfoToJSONTyped(value?: TaskProvidersInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providers': value['providers'],
        'platform': TaskProvidersInfoPlatformToJSON(value['platform']),
    };
}

