/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskProvidersInfoPlatform
 */
export interface TaskProvidersInfoPlatform {
    /**
     * 
     * @type {string}
     * @memberof TaskProvidersInfoPlatform
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskProvidersInfoPlatform
     */
    description: string;
}

/**
 * Check if a given object implements the TaskProvidersInfoPlatform interface.
 */
export function instanceOfTaskProvidersInfoPlatform(value: object): value is TaskProvidersInfoPlatform {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function TaskProvidersInfoPlatformFromJSON(json: any): TaskProvidersInfoPlatform {
    return TaskProvidersInfoPlatformFromJSONTyped(json, false);
}

export function TaskProvidersInfoPlatformFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProvidersInfoPlatform {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function TaskProvidersInfoPlatformToJSON(json: any): TaskProvidersInfoPlatform {
    return TaskProvidersInfoPlatformToJSONTyped(json, false);
}

export function TaskProvidersInfoPlatformToJSONTyped(value?: TaskProvidersInfoPlatform | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

