/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Toggle audio/video/screen-share state.
 * @export
 * @interface UpdateParticipantStateRequest
 */
export interface UpdateParticipantStateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateParticipantStateRequest
     */
    audioEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateParticipantStateRequest
     */
    videoEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateParticipantStateRequest
     */
    screenShareEnabled?: boolean;
}

/**
 * Check if a given object implements the UpdateParticipantStateRequest interface.
 */
export function instanceOfUpdateParticipantStateRequest(value: object): value is UpdateParticipantStateRequest {
    return true;
}

export function UpdateParticipantStateRequestFromJSON(json: any): UpdateParticipantStateRequest {
    return UpdateParticipantStateRequestFromJSONTyped(json, false);
}

export function UpdateParticipantStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateParticipantStateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'audioEnabled': json['audioEnabled'] == null ? undefined : json['audioEnabled'],
        'videoEnabled': json['videoEnabled'] == null ? undefined : json['videoEnabled'],
        'screenShareEnabled': json['screenShareEnabled'] == null ? undefined : json['screenShareEnabled'],
    };
}

export function UpdateParticipantStateRequestToJSON(json: any): UpdateParticipantStateRequest {
    return UpdateParticipantStateRequestToJSONTyped(json, false);
}

export function UpdateParticipantStateRequestToJSONTyped(value?: UpdateParticipantStateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audioEnabled': value['audioEnabled'],
        'videoEnabled': value['videoEnabled'],
        'screenShareEnabled': value['screenShareEnabled'],
    };
}

