/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRecordTypeRequest
 */
export interface UpdateRecordTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordTypeRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordTypeRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordTypeRequest
     */
    name_plural?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordTypeRequest
     */
    icon?: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UpdateRecordTypeRequest
     */
    attribute_schema?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the UpdateRecordTypeRequest interface.
 */
export function instanceOfUpdateRecordTypeRequest(value: object): value is UpdateRecordTypeRequest {
    return true;
}

export function UpdateRecordTypeRequestFromJSON(json: any): UpdateRecordTypeRequest {
    return UpdateRecordTypeRequestFromJSONTyped(json, false);
}

export function UpdateRecordTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecordTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'name_plural': json['name_plural'] == null ? undefined : json['name_plural'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'attribute_schema': json['attribute_schema'] == null ? undefined : json['attribute_schema'],
    };
}

export function UpdateRecordTypeRequestToJSON(json: any): UpdateRecordTypeRequest {
    return UpdateRecordTypeRequestToJSONTyped(json, false);
}

export function UpdateRecordTypeRequestToJSONTyped(value?: UpdateRecordTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'name_plural': value['name_plural'],
        'icon': value['icon'],
        'attribute_schema': value['attribute_schema'],
    };
}

