/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWorkspaceRequest
 */
export interface UpdateWorkspaceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    logoUrl?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateWorkspaceRequest
     */
    settings?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateWorkspaceRequest interface.
 */
export function instanceOfUpdateWorkspaceRequest(value: object): value is UpdateWorkspaceRequest {
    return true;
}

export function UpdateWorkspaceRequestFromJSON(json: any): UpdateWorkspaceRequest {
    return UpdateWorkspaceRequestFromJSONTyped(json, false);
}

export function UpdateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'settings': json['settings'] == null ? undefined : json['settings'],
    };
}

export function UpdateWorkspaceRequestToJSON(json: any): UpdateWorkspaceRequest {
    return UpdateWorkspaceRequestToJSONTyped(json, false);
}

export function UpdateWorkspaceRequestToJSONTyped(value?: UpdateWorkspaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
        'settings': value['settings'],
    };
}

