/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Partial update — every field optional.
 * @export
 * @interface UpdatePresentationRequest
 */
export interface UpdatePresentationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePresentationRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePresentationRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePresentationRequest
     */
    theme?: string;
}

/**
 * Check if a given object implements the UpdatePresentationRequest interface.
 */
export function instanceOfUpdatePresentationRequest(value: object): value is UpdatePresentationRequest {
    return true;
}

export function UpdatePresentationRequestFromJSON(json: any): UpdatePresentationRequest {
    return UpdatePresentationRequestFromJSONTyped(json, false);
}

export function UpdatePresentationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePresentationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'theme': json['theme'] == null ? undefined : json['theme'],
    };
}

export function UpdatePresentationRequestToJSON(json: any): UpdatePresentationRequest {
    return UpdatePresentationRequestToJSONTyped(json, false);
}

export function UpdatePresentationRequestToJSONTyped(value?: UpdatePresentationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'theme': value['theme'],
    };
}

