/* tslint:disable */
/* eslint-disable */
/**
 * SpatioAPI
 * The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceMember
 */
export interface WorkspaceMember {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceMember
     */
    id: string;
    /**
     * 
     * @type {WorkspaceMemberRoleEnum}
     * @memberof WorkspaceMember
     */
    role: WorkspaceMemberRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceMember
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceMember
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceMember
     */
    avatar?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceMember
     */
    joinedAt: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkspaceMember
     */
    user?: { [key: string]: any; };
}


/**
 * @export
 */
export const WorkspaceMemberRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member',
    Guest: 'guest'
} as const;
export type WorkspaceMemberRoleEnum = typeof WorkspaceMemberRoleEnum[keyof typeof WorkspaceMemberRoleEnum];


/**
 * Check if a given object implements the WorkspaceMember interface.
 */
export function instanceOfWorkspaceMember(value: object): value is WorkspaceMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function WorkspaceMemberFromJSON(json: any): WorkspaceMember {
    return WorkspaceMemberFromJSONTyped(json, false);
}

export function WorkspaceMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'joinedAt': (new Date(json['joinedAt'])),
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function WorkspaceMemberToJSON(json: any): WorkspaceMember {
    return WorkspaceMemberToJSONTyped(json, false);
}

export function WorkspaceMemberToJSONTyped(value?: WorkspaceMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'email': value['email'],
        'name': value['name'],
        'avatar': value['avatar'],
        'joinedAt': value['joinedAt'].toISOString(),
        'user': value['user'],
    };
}

